##**Installing the transformers library**



In [ ]:
!cat /proc/meminfo
!df -h

In [2]:
!pip install transformers

     |████████████████████████████████| 1.1MB 3.5MB/s 
     |████████████████████████████████| 1.1MB 18.3MB/s 
     |████████████████████████████████| 3.0MB 32.4MB/s 
     |████████████████████████████████| 890kB 47.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=8827e5a113115b5e2b1395ab8fa75bff722b57c0e0f948f0f8cda1a8a3cd0e71
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


##**Importing the tools**

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
import re
warnings.filterwarnings('ignore')

##**Importing the dataset from Drive**

In [4]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
df=pd.read_csv('gdrive/My Drive/Total_cleaned.csv',delimiter=';')

In [5]:
df1=pd.read_csv('gdrive/My Drive/Final_DUP.csv',delimiter=';')

In [6]:
df2=pd.read_csv('gdrive/My Drive/Final_NDUP.csv',delimiter=';')

In [ ]:
df[3]

##**Loading the Pre-trained BERT model**

In [7]:
model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

In [ ]:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')
#tokenizer = ppb.DistilBertTokenizer.from_pretrained(distil_bert, do_lower_case=True, add_special_tokens=True, max_length=128, pad_to_max_length=True)
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)
#model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')

##**Lower case**

In [ ]:
df[0]= df[0].str.lower()
df[1]= df[1].str.lower()
df[2]= df[2].str.lower()
df[3]= df[3].str.lower()
df[4]= df[4].str.lower()
df[5]= df[5].str.lower()

## **Remove Digits**

In [ ]:
df[3] = df[3].str.replace(r'0', '')
df[3] = df[3].str.replace(r'1', '')
df[3] = df[3].str.replace(r'2', '')
df[3] = df[3].str.replace(r'3', '')
df[3] = df[3].str.replace(r'4', '')
df[3] = df[3].str.replace(r'5', '')
df[3] = df[3].str.replace(r'6', '')
df[3] = df[3].str.replace(r'7', '')
df[3] = df[3].str.replace(r'8', '')
df[3] = df[3].str.replace(r'9', '')

##**Remove special characters**

In [ ]:
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r'@ ?', '')
df[3] = df[3].str.replace(r'!', '')
df[3] = df[3].str.replace(r'+', '')
df[3] = df[3].str.replace(r'-', '')
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r':', '')
df[3] = df[3].str.replace(r';', '')
df[3] = df[3].str.replace(r'>', '')
df[3] = df[3].str.replace(r'=', '')
df[3] = df[3].str.replace(r'<', '')
df[3] = df[3].str.replace(r'(', '')
df[3] = df[3].str.replace(r')', '')
df[3] = df[3].str.replace(r'#', '')
df[3] = df[3].str.replace(r'$', '')
df[3] = df[3].str.replace(r'&', '')
df[3] = df[3].str.replace(r'*', '')
df[3] = df[3].str.replace(r'%', '')
df[3] = df[3].str.replace(r'_', '')

##**Convert to String type**

In [ ]:
df[3] = pd.Series(df[3], dtype="string")  # Pblm tokenize : " Input is not valid ,Should be a string, a list/tuple of strings or a list/tuple of integers"
df[2] = pd.Series(df[2], dtype="string")
df[2] = df[2].astype("|S")
df[2].str.decode("utf-8")
df[3] = df[3].astype("|S")
df[3].str.decode("utf-8")

In [ ]:
df[3].str.len()


##**Tokenization**

In [ ]:
df.shape

In [8]:
batch_31=df1[:3000]
batch_32=df2[:3000]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[3000:6000]
batch_42=df2[3000:6000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[6000:9000]
batch_52=df2[6000:9000]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[9000:12000]
batch_62=df2[9000:12000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[12000:15000]
batch_72=df2[12000:15000]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[15000:18000]
batch_82=df2[15000:18000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[18000:21000]
batch_92=df2[18000:21000]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[21000:]
batch_102=df2[21000:]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)

In [ ]:
batch_31=df1[:4000]
batch_32=df2[:4000]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[4000:8000]
batch_42=df2[4000:8000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[8000:12000]
batch_52=df2[8000:12000]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[12000:16000]
batch_62=df2[12000:16000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[16000:20000]
batch_72=df2[16000:20000]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[20000:24000]
batch_82=df2[20000:24000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)


In [9]:
def _get_segments3(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    first_sep = False
    current_segment_id = 0 
    for token in tokens:
        segments.append(current_segment_id)
        #print(token)
        if token == 102:
            #if first_sep:
                #first_sep = False 
            #else:
           current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

#**df3**

In [10]:
pair3= df3['Title1'] + [" [SEP] "] + df3['Title2'] 
tokenized3 = pair3.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [11]:
max_len3 = 0                 # padding all lists to the same size
for i in tokenized3.values:
    if len(i) > max_len3:
        max_len3 = len(i)

In [12]:
max_len3 =120
padded3 = np.array([i + [0]*(max_len3-len(i)) for i in tokenized3.values])

np.array(padded3).shape  

(6000, 120)

In [13]:
attention_mask3 = np.where(padded3 != 0, 1, 0)
attention_mask3.shape
input_ids3 = torch.tensor(padded3)  
attention_mask3 = torch.tensor(attention_mask3)

In [14]:
input_segments3= np.array([_get_segments3(token, max_len3)for token in tokenized3.values])


In [15]:
token_type_ids3 = torch.tensor(input_segments3)
input_segments3 = torch.tensor(input_segments3)

In [16]:
with torch.no_grad():
    last_hidden_states3 = model(input_ids3, attention_mask=attention_mask3, token_type_ids=input_segments3)    # <<< 600 rows only !!!

In [ ]:
with torch.no_grad():
    last_hidden_states3 = model(input_ids3, attention_mask=attention_mask3)

NameError: ignored

In [17]:
features3 = last_hidden_states3[0][:,0,:].numpy()
features3

array([[-1.186057  , -0.10142776, -0.59978235, ..., -0.9827655 ,
         0.09031001,  0.64574486],
       [-1.113508  , -0.19371924, -0.71273744, ..., -1.0534436 ,
         0.1270571 ,  0.47058022],
       [-1.0932132 , -0.16971353, -0.81159365, ..., -0.8816474 ,
         0.14476167,  0.50101566],
       ...,
       [-0.5754788 ,  0.08482695, -0.7166544 , ..., -0.62770295,
        -0.1097972 ,  0.6740445 ],
       [-1.0201509 , -0.12085654, -0.21943487, ..., -0.9099933 ,
        -0.2597822 ,  0.74342537],
       [-0.7015321 , -0.40521187, -0.6403048 , ..., -0.6998733 ,
        -0.23273611,  0.3268862 ]], dtype=float32)

#**df4**

In [18]:
pair4= df4['Title1'] + [" [SEP] "] + df4['Title2'] 
tokenized4 = pair4.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [19]:
max_len4 = 0                 # padding all lists to the same size
for i in tokenized4.values:
    if len(i) > max_len4:
        max_len4 = len(i)

In [20]:
max_len4 =120
padded4 = np.array([i + [0]*(max_len4-len(i)) for i in tokenized4.values])

np.array(padded4).shape  

(6000, 120)

In [21]:
attention_mask4 = np.where(padded4 != 0, 1, 0)
attention_mask4.shape
input_ids4 = torch.tensor(padded4)  
attention_mask4 = torch.tensor(attention_mask4)

In [ ]:
def _get_segments3(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    first_sep = False
    current_segment_id = 0 
    for token in tokens:
        segments.append(current_segment_id)
        #print(token)
        if token == 102:
            #if first_sep:
                #first_sep = False 
            #else:
           current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

In [22]:
input_segments4= np.array([_get_segments3(token, max_len4)for token in tokenized4.values])


In [23]:
token_type_ids4 = torch.tensor(input_segments4)
input_segments4 = torch.tensor(input_segments4)

In [24]:
with torch.no_grad():
    last_hidden_states4 = model(input_ids4, attention_mask=attention_mask4, token_type_ids=input_segments4)    # <<< 600 rows only !!!

In [25]:
features4 = last_hidden_states4[0][:,0,:].numpy()
features4

array([[-0.97640496, -0.17567202, -0.58533573, ..., -0.62893546,
         0.23321687,  0.38595852],
       [-0.6628797 , -0.03105273, -0.7753756 , ..., -0.50868565,
        -0.07407893,  0.5346418 ],
       [-0.88881224, -0.13224594, -0.3883576 , ..., -0.76214963,
         0.02098887,  0.69485253],
       ...,
       [-0.7717968 ,  0.0551487 , -0.57811445, ..., -0.9994336 ,
        -0.27345043,  0.99331915],
       [-0.512229  , -0.3493    , -0.47361088, ..., -0.7135849 ,
         0.00845438,  0.6855976 ],
       [-0.6086248 , -0.20416647, -0.27081123, ..., -0.56838787,
         0.12452374,  0.56750035]], dtype=float32)

#**df5**

In [26]:
pair5= df5['Title1'] + [" [SEP] "] + df5['Title2'] 

In [27]:
tokenized5 = pair5.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
pair5.shape
tokenized5.shape

(6000,)

##**Padding**

In [28]:
max_len5 = 0                 # padding all lists to the same size
for i in tokenized5.values:
    if len(i) > max_len5:
        max_len5 = len(i)

In [29]:
max_len5 =120

In [30]:
padded5 = np.array([i + [0]*(max_len5-len(i)) for i in tokenized5.values])

np.array(padded5).shape        # Dimensions of the padded variable

(6000, 120)

##**Masking**

In [31]:
attention_mask5 = np.where(padded5 != 0, 1, 0)
attention_mask5.shape
input_ids5 = torch.tensor(padded5)  
attention_mask5 = torch.tensor(attention_mask5)

In [ ]:
input_ids[0] ######## TITLE 2

tensor([  101, 13764,  6279,  5144,  3791,  2000,  2022,  6086,  1999,  3653,
        10343,   102,  2543, 14876,  2595, 11896,  2000,  2272,  2067,  2044,
        23818,  5724,  2109,  1041,  1012,  1043,  1012,  1999,  5587,  2239,
        10651,   102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0])

##**Running the `model()` function through BERT**

In [ ]:
def _get_segments3(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    first_sep = False
    current_segment_id = 0 
    for token in tokens:
        segments.append(current_segment_id)
        #print(token)
        if token == 102:
            #if first_sep:
                #first_sep = False 
            #else:
           current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

In [32]:
input_segments5= np.array([_get_segments3(token, max_len5)for token in tokenized5.values])

In [33]:
token_type_ids5 = torch.tensor(input_segments5)
input_segments5 = torch.tensor(input_segments5)

In [34]:
with torch.no_grad():
    last_hidden_states5 = model(input_ids5, attention_mask=attention_mask5, token_type_ids=input_segments5)    # <<< 600 rows only !!!

##**Slicing the part of the output of BERT : [cls]**

In [35]:
features5 = last_hidden_states5[0][:,0,:].numpy()
features5

array([[-1.0968552e+00, -1.1498391e-04, -1.8097033e-01, ...,
        -1.0345995e+00,  1.3936336e-01,  5.3766835e-01],
       [-9.7731698e-01, -6.9209188e-02, -2.8442854e-01, ...,
        -1.0574378e+00,  1.5433541e-01,  5.2988535e-01],
       [-5.1702094e-01,  8.6537391e-02, -4.3555906e-01, ...,
        -1.2390417e+00,  5.0639510e-01,  6.3943839e-01],
       ...,
       [-6.4818454e-01, -1.3875425e-01, -4.0637827e-01, ...,
        -7.2697443e-01,  4.8434146e-02,  7.5000584e-01],
       [-5.0137037e-01,  2.1840182e-01, -2.9392228e-01, ...,
        -8.9454490e-01,  3.6958344e-02,  7.2090042e-01],
       [-7.5184339e-01, -3.6516461e-01,  3.2815051e-01, ...,
        -7.9710126e-01, -3.7424535e-02,  6.1670935e-01]], dtype=float32)

#**df6**

In [36]:
pair6= df6['Title1'] + [" [SEP] "] + df6['Title2'] 
tokenized6 = pair6.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len6 = 0                 # padding all lists to the same size
for i in tokenized6.values:
    if len(i) > max_len6:
        max_len6 = len(i)

In [37]:
max_len6=120

In [38]:
padded6 = np.array([i + [0]*(max_len6-len(i)) for i in tokenized6.values])

np.array(padded6).shape        # Dimensions of the padded variable

(6000, 120)

In [39]:
attention_mask6 = np.where(padded6 != 0, 1, 0)
attention_mask6.shape
input_ids6 = torch.tensor(padded6)  
attention_mask6 = torch.tensor(attention_mask6)

In [40]:
input_segments6= np.array([_get_segments3(token, max_len6)for token in tokenized6.values])

In [41]:
token_type_ids6 = torch.tensor(input_segments6)
input_segments6 = torch.tensor(input_segments6)

In [42]:
with torch.no_grad():
    last_hidden_states6 = model(input_ids6, attention_mask=attention_mask6, token_type_ids=input_segments6)    # <<< 600 rows only !!!

In [43]:
features6 = last_hidden_states6[0][:,0,:].numpy()
features6

array([[-0.8601473 , -0.2977435 , -0.29706708, ..., -0.42109537,
         0.0869902 ,  0.36556628],
       [-0.8803269 , -0.34002325, -0.32057354, ..., -0.3704867 ,
         0.11473913,  0.53997093],
       [-0.7956574 , -0.13639633, -0.36664516, ..., -0.6120657 ,
         0.06846947,  0.43598878],
       ...,
       [-0.42677477, -0.38272762, -0.32202992, ..., -0.70686007,
        -0.28220966,  0.91326624],
       [-0.3934263 , -0.02559741, -0.2190588 , ..., -0.75262606,
         0.10670976,  0.57626104],
       [-0.24185057,  0.11521484, -0.00239121, ..., -0.7431041 ,
         0.47558734,  0.25420588]], dtype=float32)

#**df7**

In [44]:
pair7= df7['Title1'] + [" [SEP] "] + df7['Title2'] 
tokenized7 = pair7.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [45]:
max_len7 = 0                 # padding all lists to the same size
for i in tokenized7.values:
    if len(i) > max_len7:
        max_len7 = len(i)

In [46]:
max_len7=120

In [47]:
padded7 = np.array([i + [0]*(max_len7-len(i)) for i in tokenized7.values])

np.array(padded7).shape        # Dimensions of the padded variable

(6000, 120)

In [48]:
attention_mask7 = np.where(padded7 != 0, 1, 0)
attention_mask7.shape
input_ids7 = torch.tensor(padded7)  
attention_mask7 = torch.tensor(attention_mask7)

In [49]:
input_segments7= np.array([_get_segments3(token, max_len7)for token in tokenized7.values])

In [50]:
token_type_ids7 = torch.tensor(input_segments7)
input_segments7 = torch.tensor(input_segments7)

In [51]:
with torch.no_grad():
    last_hidden_states7 = model(input_ids7, attention_mask=attention_mask7, token_type_ids=input_segments7)    # <<< 600 rows only !!!

In [52]:
features7 = last_hidden_states7[0][:,0,:].numpy()
features7

array([[-1.2536876 , -0.2829948 , -0.49233016, ..., -0.44757465,
         0.16582265,  0.26805934],
       [-0.8591346 , -0.0954482 , -0.717904  , ..., -0.62488824,
        -0.10363079,  0.56468713],
       [-0.92200935, -0.05246457, -0.48387682, ..., -0.45409232,
        -0.05936138,  0.68349785],
       ...,
       [-0.5780965 , -0.46829298, -0.22179726, ..., -0.8665547 ,
        -0.31438905,  0.6482919 ],
       [-0.36891255, -0.33693248,  0.04028825, ..., -0.49497795,
         0.04332091,  0.5287879 ],
       [-0.42365998,  0.18583986, -0.05957045, ..., -0.92423004,
         0.55336   ,  0.5910974 ]], dtype=float32)

#**df8**

In [ ]:
pair8= df8['Title1'] + [" [SEP] "] + df8['Title2'] 
tokenized8 = pair8.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len8 = 0                 # padding all lists to the same size
for i in tokenized8.values:
    if len(i) > max_len8:
        max_len8 = len(i)

In [ ]:
max_len8=120
padded8 = np.array([i + [0]*(max_len8-len(i)) for i in tokenized8.values])

np.array(padded8).shape        # Dimensions of the padded variable

(6000, 120)

In [ ]:
attention_mask8 = np.where(padded8 != 0, 1, 0)
attention_mask8.shape
input_ids8 = torch.tensor(padded8)  
attention_mask8 = torch.tensor(attention_mask8)

In [ ]:
input_segments8= np.array([_get_segments3(token, max_len8)for token in tokenized8.values])

In [ ]:
token_type_ids8 = torch.tensor(input_segments8)
input_segments8 = torch.tensor(input_segments8)

In [ ]:
with torch.no_grad():
    last_hidden_states8 = model(input_ids8, attention_mask=attention_mask8, token_type_ids=input_segments8)    # <<< 600 rows only !!!

In [ ]:
features8 = last_hidden_states8[0][:,0,:].numpy()
features8

#**df9**

In [ ]:
pair9= df9['Title1'] + [" [SEP] "] + df9['Title2'] 
tokenized9 = pair9.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len9 = 0                 # padding all lists to the same size
for i in tokenized9.values:
    if len(i) > max_len9:
        max_len9 = len(i)

In [ ]:
max_len9=120
padded9 = np.array([i + [0]*(max_len9-len(i)) for i in tokenized9.values])

np.array(padded9).shape        # Dimensions of the padded variable

(6000, 120)

In [ ]:
attention_mask9 = np.where(padded9 != 0, 1, 0)
attention_mask9.shape
input_ids9 = torch.tensor(padded9)  
attention_mask9 = torch.tensor(attention_mask9)

In [ ]:
input_segments9= np.array([_get_segments3(token, max_len9)for token in tokenized9.values])

In [ ]:
token_type_ids9 = torch.tensor(input_segments9)
input_segments9 = torch.tensor(input_segments9)

In [ ]:
with torch.no_grad():
    last_hidden_states9 = model(input_ids9, attention_mask=attention_mask9, token_type_ids=input_segments9)    

In [ ]:
features9 = last_hidden_states9[0][:,0,:].numpy()
features9

#**df10**

In [ ]:
pair10= df10['Title1'] + [" [SEP] "] + df10['Title2'] 
tokenized10 = pair10.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len10 = 0                 # padding all lists to the same size
for i in tokenized10.values:
    if len(i) > max_len10:
        max_len10 = len(i)

In [ ]:
max_len10=120
padded10 = np.array([i + [0]*(max_len10-len(i)) for i in tokenized10.values])

np.array(padded10).shape        # Dimensions of the padded variable

In [ ]:
attention_mask10 = np.where(padded10 != 0, 1, 0)
attention_mask10.shape
input_ids10 = torch.tensor(padded10)  
attention_mask10 = torch.tensor(attention_mask10)

In [ ]:
input_segments10= np.array([_get_segments3(token, max_len10)for token in tokenized10.values])

In [ ]:
token_type_ids10 = torch.tensor(input_segments10)
input_segments10 = torch.tensor(input_segments10)

In [ ]:
with torch.no_grad():
    last_hidden_states10 = model(input_ids10, attention_mask=attention_mask10, token_type_ids=input_segments10)    # <<< 600 rows only !!!

In [ ]:
features10 = last_hidden_states10[0][:,0,:].numpy()
features10

#**Classification**

In [53]:
features=np.concatenate([features3,features4,features5,features6,features7])

In [ ]:
features=features3

In [ ]:
features.shape

(6000, 768)

In [54]:
Total = pd.concat([df3,df4,df5,df6,df7], ignore_index=True)

In [ ]:
Total

In [ ]:
labels =df3['Label']

In [55]:
labels =Total['Label']

In [ ]:
labels

In [56]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels,test_size=0.2,random_state=42)

In [ ]:
train_labels.shape
test_labels.shape
test_features.shape

#**LogisticRegression best params**

In [107]:
#n_splits=2
#cross_val_score=5
parameters = {'C': np.linspace(0.0001, 100, 20)}
grid_search = GridSearchCV(LogisticRegression(), parameters, cv=5)
grid_search.fit(train_features, train_labels)
print('best parameters: ', grid_search.best_params_)
print('best scrores: ', grid_search.best_score_)

best parameters:  {'C': 36.842168421052634}
best scrores:  0.8771666666666667


In [108]:
lr_clf = LogisticRegression(C=36.84)
lr_clf.fit(train_features, train_labels)


LogisticRegression(C=36.84, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [109]:
lr_clf.score(test_features, test_labels)

0.8881666666666667

In [110]:
y_predLr = lr_clf.predict(test_features)

In [111]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_predLr))
print(confusion_matrix(test_labels, y_predLr))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      3005
           1       0.90      0.88      0.89      2995

    accuracy                           0.89      6000
   macro avg       0.89      0.89      0.89      6000
weighted avg       0.89      0.89      0.89      6000

[[2706  299]
 [ 372 2623]]


In [61]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_features,test_labels))
print(classification_report(test_features,test_labels))

ValueError: ignored

In [ ]:
def get_classification_metric(testy, probs):
    from sklearn.metrics import precision_recall_curve
    precision, recall, thresholds = precision_recall_curve(testy, probs[:,1])
    # convert to f score
    fscore = (2 * precision * recall) / (precision + recall)
    # locate the index of the largest f score
    ix = np.argmax(fscore)
    return fscore[ix]

In [ ]:
metric=get_classification_metric

In [62]:
scores = cross_val_score(lr_clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.865 (std: 0.010)



In [ ]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier()

scores = cross_val_score(clf, train_features, train_labels)
print("Dummy classifier score: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Dummy classifier score: 0.500 (+/- 0.02)


In [ ]:
df.fillna(0) # Pblm de Nan 

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

In [ ]:
clf.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = clf.predict(test_features)

In [ ]:
y_pred

In [ ]:
###############""""""""""""""
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(test_features, y_pred))

#**Decision tree**

In [112]:
from sklearn.tree import DecisionTreeClassifier

In [113]:
clf = DecisionTreeClassifier(max_depth = 2, random_state = 0,criterion='gini')

In [114]:
clf.fit(train_features, train_labels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [115]:
y_preddt = clf.predict(test_features)

In [116]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_preddt))
print(confusion_matrix(test_labels, y_preddt))

              precision    recall  f1-score   support

           0       0.84      0.77      0.80      3005
           1       0.79      0.85      0.82      2995

    accuracy                           0.81      6000
   macro avg       0.81      0.81      0.81      6000
weighted avg       0.81      0.81      0.81      6000

[[2320  685]
 [ 456 2539]]


In [66]:
# Predict for 1 observation
clf.predict(test_features)
# Predict for multiple observations
#clf.predict(test_features[0:200])

array([1, 0, 0, ..., 0, 1, 0])

In [67]:
# The score method returns the accuracy of the model
score = clf.score(test_features, test_labels)
print(score)

0.8098333333333333


In [68]:
scores = cross_val_score(clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.814 (std: 0.012)



#**SVM**

In [69]:
from sklearn.svm import SVC

In [70]:

svclassifier = SVC(kernel='linear')
svclassifier.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [71]:
y_pred = svclassifier.predict(test_features)

In [72]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[2767  238]
 [ 396 2599]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90      3005
           1       0.92      0.87      0.89      2995

    accuracy                           0.89      6000
   macro avg       0.90      0.89      0.89      6000
weighted avg       0.90      0.89      0.89      6000



In [ ]:
param_grid = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=15.0min
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 15.0min remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.8min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.9min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.6min
[CV] C=1, gamma=1, kernel=rbf ........................................


In [ ]:
grid.best_params_

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

#Cross_Val_SVC

In [73]:
from sklearn.model_selection import cross_val_score

In [76]:
from sklearn import svm

In [77]:
clf = svm.SVC(kernel='linear', C=36.84)

In [78]:
scores = cross_val_score(clf, test_labels, y_pred, cv=5)

In [79]:
scores = cross_val_score(clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.850 (std: 0.011)



#**MLP Best params**

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=100)
from sklearn.datasets import make_classification

In [ ]:
parameter_space = {
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(train_features, train_labels)

GridSearchCV(cv=3, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=100, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state...
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'activation': ['ta

In [ ]:
# Best paramete set
print('Best parameters found:\n', clf.best_params_)

# All results
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))


Best parameters found:
 {'activation': 'tanh', 'alpha': 0.05, 'hidden_layer_sizes': (100,), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.878 (+/-0.004) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.876 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'adam'}
0.877 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.876 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.878 (+/-0.004) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.874 (+/-0.006) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'adam'

In [ ]:
y_true, y_pred = test_labels , clf.predict(test_features)

from sklearn.metrics import classification_report, confusion_matrix
print('Results on the test set:')
print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

Results on the test set:
              precision    recall  f1-score   support

           0       0.90      0.89      0.90      3005
           1       0.89      0.91      0.90      2995

    accuracy                           0.90      6000
   macro avg       0.90      0.90      0.90      6000
weighted avg       0.90      0.90      0.90      6000

[[2667  338]
 [ 280 2715]]


In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(train_features, train_labels)
clf.predict_proba(test_features[:1])

array([[1.51787609e-08, 9.99999985e-01]])

In [ ]:
clf.predict(test_features[:1000, :])

In [ ]:
clf.score(test_features, test_labels)

0.8841666666666667

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
clf = MLPClassifier.mlp(kernel='linear')

AttributeError: ignored

In [ ]:
scores = cross_val_score(clf, test_labels, y_pred, cv=5)

In [ ]:

scores = cross_val_score(clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.872 (std: 0.014)



#**Random Forest**

In [102]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(train_features, train_labels)
y_pred1 = regressor.predict(test_features)

In [ ]:
y_pred

array([0, 1, 1, ..., 0, 1, 0])

In [ ]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(test_features, y_pred1))

In [103]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred1))
print(confusion_matrix(test_labels, y_pred1))

ValueError: ignored

#**Naive Bayes**

#Gaussian

In [92]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_features, train_labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [93]:
y_pred = gnb.predict(test_features)

In [94]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(test_labels, y_pred))

Accuracy: 0.8358333333333333


In [95]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred))
print(confusion_matrix(test_labels, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84      3005
           1       0.83      0.84      0.84      2995

    accuracy                           0.84      6000
   macro avg       0.84      0.84      0.84      6000
weighted avg       0.84      0.84      0.84      6000

[[2495  510]
 [ 475 2520]]


*Cross Validation*

In [96]:
scores = cross_val_score(gnb, test_labels, y_pred, cv=5)
scores = cross_val_score(gnb, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.836 (std: 0.011)



#Bernoulli:

In [97]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB(binarize=0.0)
bnb.fit(train_features, train_labels)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [98]:
print("Score: ",bnb.score(test_features, test_labels))

Score:  0.829


In [101]:
scores = cross_val_score(bnb, test_labels, y_pred, cv=5)
scores = cross_val_score(bnb, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.831 (std: 0.012)



*Cross Validation*

In [ ]:
print("Cross Validation:",cross_val_score(bnb, digits.data, digits.target, scoring='accuracy', cv=10).mean())

NameError: ignored

#Multinomial

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(train_features, train_labels)
mnb.score(test_features, test_labels)

In [ ]:
mnb = MultinomialNB()
cross_val_score(mnb, digits.data, digits.target, scoring='accuracy', cv=10).mean()


0.8797858472998138

#Best params SVC

In [ ]:
from sklearn.svm import SVC

In [ ]:
model = SVC()

In [ ]:
model.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction = model.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,prediction))
print(confusion_matrix(test_labels, prediction))

              precision    recall  f1-score   support

           0       0.82      0.94      0.88       587
           1       0.93      0.81      0.87       613

    accuracy                           0.87      1200
   macro avg       0.88      0.87      0.87      1200
weighted avg       0.88      0.87      0.87      1200

[[551  36]
 [117 496]]


In [ ]:
param_grid = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}


In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=   7.7s
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.7s remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=   7.2s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   7.2s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   7.8s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   7.3s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  21.2s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  20.9s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=  20.6s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] .

[Parallel(n_jobs=1)]: Done 160 out of 160 | elapsed: 34.7min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.001, 0.0001],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [ ]:
grid.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90       587
           1       0.95      0.85      0.90       613

    accuracy                           0.90      1200
   macro avg       0.91      0.90      0.90      1200
weighted avg       0.91      0.90      0.90      1200

[[558  29]
 [ 89 524]]


#**Random Forest Best params**

In [84]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(random_state=42)

In [85]:
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [ ]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(train_features, train_labels)

In [ ]:
CV_rfc.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'max_features': 'auto',
 'n_estimators': 500}

In [ ]:
rfc1=RandomForestClassifier(random_state=42, max_features='auto', n_estimators= 200, max_depth=8, criterion='gini')

In [ ]:
rfc1.fit(train_features, train_labels)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:

pred=rfc1.predict(test_features)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy for Random Forest on CV data: ",accuracy_score(test_labels,pred))

Accuracy for Random Forest on CV data:  0.8441666666666666


In [ ]:
from dnn_classifier import DNNClassifier

In [87]:
import xgboost as xgb
model=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
model.fit(train_features, train_labels)


0.847

In [89]:
model.score(test_features,test_labels)


0.847

In [90]:
scores = cross_val_score(model, test_labels, test_features, cv=5)

In [91]:
scores = cross_val_score(model, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.847 (std: 0.012)

