##**Installing the transformers library**



In [ ]:
!pip install transformers

##**Importing the tools**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
import re
warnings.filterwarnings('ignore')

##**Importing the dataset from Drive**

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
df=pd.read_csv('gdrive/My Drive/Total_cleaned.csv',delimiter=';')

In [ ]:
df1=pd.read_csv('gdrive/My Drive/Final_DUP.csv',delimiter=';')

In [ ]:
df2=pd.read_csv('gdrive/My Drive/Final_NDUP.csv',delimiter=';')

In [ ]:
df1=pd.read_csv('gdrive/My Drive/cln_copie_dup_total1.csv',delimiter=';')

In [ ]:
df2=pd.read_csv('gdrive/My Drive/cln_copie_nndup_total1.csv',delimiter=';')

##**Loading the Pre-trained BERT model**

In [ ]:
model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

##**Lower case**

In [ ]:
df[0]= df[0].str.lower()
df[1]= df[1].str.lower()
df[2]= df[2].str.lower()
df[3]= df[3].str.lower()
df[4]= df[4].str.lower()
df[5]= df[5].str.lower()

## **Remove Digits**

In [ ]:
df[3] = df[3].str.replace(r'0', '')
df[3] = df[3].str.replace(r'1', '')
df[3] = df[3].str.replace(r'2', '')
df[3] = df[3].str.replace(r'3', '')
df[3] = df[3].str.replace(r'4', '')
df[3] = df[3].str.replace(r'5', '')
df[3] = df[3].str.replace(r'6', '')
df[3] = df[3].str.replace(r'7', '')
df[3] = df[3].str.replace(r'8', '')
df[3] = df[3].str.replace(r'9', '')

##**Remove special characters**

In [ ]:
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r'@ ?', '')
df[3] = df[3].str.replace(r'!', '')
df[3] = df[3].str.replace(r'+', '')
df[3] = df[3].str.replace(r'-', '')
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r':', '')
df[3] = df[3].str.replace(r';', '')
df[3] = df[3].str.replace(r'>', '')
df[3] = df[3].str.replace(r'=', '')
df[3] = df[3].str.replace(r'<', '')
df[3] = df[3].str.replace(r'(', '')
df[3] = df[3].str.replace(r')', '')
df[3] = df[3].str.replace(r'#', '')
df[3] = df[3].str.replace(r'$', '')
df[3] = df[3].str.replace(r'&', '')
df[3] = df[3].str.replace(r'*', '')
df[3] = df[3].str.replace(r'%', '')
df[3] = df[3].str.replace(r'_', '')

In [ ]:
df2.shape

(17005, 7)

##**Convert to String type**

In [ ]:
df[3] = pd.Series(df[3], dtype="string")  # Pblm tokenize : " Input is not valid ,Should be a string, a list/tuple of strings or a list/tuple of integers"
df[2] = pd.Series(df[2], dtype="string")
df[2] = df[2].astype("|S")
df[2].str.decode("utf-8")
df[3] = df[3].astype("|S")
df[3].str.decode("utf-8")

In [ ]:
df[3].str.len()


##**Tokenization**

In [ ]:
batch_31=df1[:2000]
batch_32=df2[:2000]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[2000:4000]
batch_42=df2[2000:4000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[000:6000]
batch_52=df2[4000:6000]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[6000:8000]
batch_62=df2[6000:8000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[12000:15000]
batch_72=df2[12000:15000]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[15000:18000]
batch_82=df2[15000:18000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[18000:21000]
batch_92=df2[18000:21000]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[21000:]
batch_102=df2[21000:]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)

In [ ]:
batch_31=df1[:2000]
batch_32=df2[:2000]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[2000:4000]
batch_42=df2[2000:4000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[4000:6000]
batch_52=df2[4000:6000]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[6000:8000]
batch_62=df2[6000:8000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[8000:10000]
batch_72=df2[8000:10000]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[10000:12000]
batch_82=df2[10000:12000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[12000:14000]
batch_92=df2[12000:14000]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[14000:16000]
batch_102=df2[14000:16000]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)
batch_111=df1[16000:18000]
batch_112=df2[16000:18000]
df11 = pd.concat([batch_101,batch_102], ignore_index=True)

In [ ]:
def _get_segments3(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    first_sep = False
    current_segment_id = 0 
    for token in tokens:
        segments.append(current_segment_id)
        #print(token)
        if token == 102:
            #if first_sep:
                #first_sep = False 
            #else:
           current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

#**df3**

In [ ]:
pair3= df3['Title1'] + [" [SEP] "] + df3['Description1']+ [" [SEP] "] + df3['Title2'] + [" [SEP] "] + df3['Description2']
tokenized3 = pair3.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len3 = 0                 # padding all lists to the same size
for i in tokenized3.values:
    if len(i) > max_len3:
        max_len3 = len(i)

In [ ]:
max_len3 =120
padded3 = np.array([i + [0]*(max_len3-len(i)) for i in tokenized3.values])

np.array(padded3).shape  

(4000,)

In [ ]:
padded3

array([list([101, 8902, 6415, 2987, 2102, 6611, 2593, 16129, 1012, 12139, 2030, 20116, 2015, 6782, 2000, 4442, 1999, 2008, 5930, 102, 1999, 1996, 2742, 3931, 2156, 24471, 2140, 1045, 2031, 2699, 2000, 20018, 25705, 2035, 1996, 4442, 2478, 8902, 11748, 23773, 14399, 6097, 9587, 5831, 4571, 1012, 1998, 2663, 2543, 14876, 2595, 1012, 2119, 10580, 2023, 3291, 2061, 2009, 3849, 2000, 2022, 3243, 2019, 2214, 3277, 1012, 2009, 2453, 2022, 3141, 2000, 11829, 2295, 1045, 2123, 2102, 2903, 2008, 9411, 2007, 11748, 23773, 1012, 1996, 3931, 8299, 9834, 8663, 7559, 1012, 5658, 15630, 21906, 7630, 16529, 2036, 3065, 2008, 8902, 2180, 2102, 6611, 4281, 8604, 2000, 4442, 2593, 2004, 2092, 2004, 2025, 4637, 11748, 23773, 1996, 2878, 2187, 5930, 2003, 3214, 2000, 2022, 2665, 2021, 9587, 2480, 10273, 14876, 2595, 2180, 2102, 4653, 1996, 6120, 2023, 2003, 4298, 11829, 1012, 1045, 2031, 2699, 2000, 2224, 20116, 2015, 2612, 2478, 7471, 11475, 16206, 2612, 1997, 11748, 23773, 1045, 2699, 11243, 2806, 16874, 

In [ ]:
attention_mask3 = np.where(padded3 != 0, 1, 0)
attention_mask3.shape
input_ids3 = torch.tensor(padded3)  
attention_mask3 = torch.tensor(attention_mask3)

TypeError: ignored

In [ ]:
input_segments3= np.array([_get_segments3(token, max_len3)for token in tokenized3.values])


In [ ]:
token_type_ids3 = torch.tensor(input_segments3)
input_segments3 = torch.tensor(input_segments3)

In [ ]:
with torch.no_grad():
    last_hidden_states3 = model(input_ids3, attention_mask=attention_mask3, token_type_ids=input_segments3)    # <<< 600 rows only !!!

In [ ]:
features3 = last_hidden_states3[0][:,0,:].numpy()
features3

array([[-1.186057  , -0.10142776, -0.59978235, ..., -0.9827655 ,
         0.09031001,  0.64574486],
       [-1.113508  , -0.19371924, -0.71273744, ..., -1.0534436 ,
         0.1270571 ,  0.47058022],
       [-1.0932132 , -0.16971353, -0.81159365, ..., -0.8816474 ,
         0.14476167,  0.50101566],
       ...,
       [-0.3883895 , -0.0799881 , -0.12448221, ..., -0.7912889 ,
         0.4300244 ,  0.58795065],
       [-0.46088067, -0.14262334, -0.4987646 , ..., -0.6428149 ,
        -0.39324462,  0.61263055],
       [-0.27448067,  0.2495448 , -0.21871285, ..., -0.4716652 ,
         0.49822754,  0.7156243 ]], dtype=float32)

#**df4**

In [ ]:
pair4=df4['Title1'] + [" [SEP] "] + df4['Description1']+ [" [SEP] "] + df4['Title2'] + [" [SEP] "] + df4['Description2']

In [ ]:
tokenized4 = pair4.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
pair4= df4['Title1'] + [" [SEP] "] + df4['Title2'] 
tokenized4 = pair4.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len4 = 0                 # padding all lists to the same size
for i in tokenized4.values:
    if len(i) > max_len4:
        max_len4 = len(i)

In [ ]:
max_len4

512

In [ ]:
max_len4 =512
padded4 = np.array([i + [0]*(max_len4-len(i)) for i in tokenized4.values])

np.array(padded4).shape  

(4000, 512)

In [ ]:
attention_mask4 = np.where(padded4 != 0, 1, 0)
attention_mask4.shape
input_ids4 = torch.tensor(padded4)  
attention_mask4 = torch.tensor(attention_mask4)

In [ ]:
input_segments4= np.array([_get_segments3(token, max_len4)for token in tokenized4.values])


In [ ]:
token_type_ids4 = torch.tensor(input_segments4)
input_segments4 = torch.tensor(input_segments4)

In [ ]:
with torch.no_grad():
    last_hidden_states4 = model(input_ids4, attention_mask=attention_mask4, token_type_ids=input_segments4)    # <<< 600 rows only !!!

In [ ]:
features4 = last_hidden_states4[0][:,0,:].numpy()
features4

array([[-1.0179603 , -0.17189638, -0.577212  , ..., -0.80530745,
         0.23091058,  0.51955557],
       [-1.065374  , -0.12674676, -0.58758795, ..., -0.88927   ,
         0.34015045,  0.25828722],
       [-1.1926316 , -0.23810454, -0.67579734, ..., -0.7927142 ,
         0.25580314,  0.29269335],
       ...,
       [-0.50465184,  0.13241628, -0.460936  , ..., -0.89873475,
        -0.08062908,  0.5726746 ],
       [-0.84563226,  0.0197216 , -0.3724658 , ..., -0.7765523 ,
        -0.17060527,  0.30317357],
       [-0.90151685,  0.02108414, -0.5548543 , ..., -0.64024544,
        -0.22410911,  0.3156242 ]], dtype=float32)

#**df5**

In [ ]:
pair5= df5['Title1'] + [" [SEP] "] + df5['Title2'] 

In [ ]:
tokenized5 = pair5.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

##**Padding**

In [ ]:
max_len5 = 0                 # padding all lists to the same size
for i in tokenized5.values:
    if len(i) > max_len5:
        max_len5 = len(i)

In [ ]:
max_len5 =120

In [ ]:
padded5 = np.array([i + [0]*(max_len5-len(i)) for i in tokenized5.values])

np.array(padded5).shape        # Dimensions of the padded variable

(4000, 120)

##**Masking**

In [ ]:
attention_mask5 = np.where(padded5 != 0, 1, 0)
attention_mask5.shape
input_ids5 = torch.tensor(padded5)  
attention_mask5 = torch.tensor(attention_mask5)

In [ ]:
input_ids[0] ######## TITLE 2

tensor([  101, 13764,  6279,  5144,  3791,  2000,  2022,  6086,  1999,  3653,
        10343,   102,  2543, 14876,  2595, 11896,  2000,  2272,  2067,  2044,
        23818,  5724,  2109,  1041,  1012,  1043,  1012,  1999,  5587,  2239,
        10651,   102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0])

##**Running the `model()` function through BERT**

In [ ]:
input_segments5= np.array([_get_segments3(token, max_len5)for token in tokenized5.values])

In [ ]:
token_type_ids5 = torch.tensor(input_segments5)
input_segments5 = torch.tensor(input_segments5)

In [ ]:
with torch.no_grad():
    last_hidden_states5 = model(input_ids5, attention_mask=attention_mask5, token_type_ids=input_segments5)    # <<< 600 rows only !!!

##**Slicing the part of the output of BERT : [cls]**

In [ ]:
features5 = last_hidden_states5[0][:,0,:].numpy()
features5

array([[-0.92297226, -0.23500037, -0.64899325, ..., -0.76961255,
         0.01562495,  0.24108753],
       [-1.038554  , -0.07274636, -0.5117236 , ..., -0.54026026,
        -0.06595104,  0.5447967 ],
       [-0.8397303 , -0.16655429, -0.60451084, ..., -0.7758954 ,
        -0.03198691,  0.4792594 ],
       ...,
       [-0.5695913 , -0.22938752, -0.5805612 , ..., -0.93466073,
        -0.29047012,  1.0487854 ],
       [-0.4453993 , -0.18653981, -0.07773766, ..., -0.7268817 ,
         0.3377998 ,  0.5721801 ],
       [-0.97925454,  0.08279418,  0.10171669, ..., -0.9305863 ,
        -0.04646008,  0.15990576]], dtype=float32)

#**df6**

In [ ]:
pair6= df6['Title1'] + [" [SEP] "] + df6['Title2'] 
tokenized6 = pair6.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len6 = 0                 # padding all lists to the same size
for i in tokenized6.values:
    if len(i) > max_len6:
        max_len6 = len(i)

In [ ]:
max_len6=120

In [ ]:
padded6 = np.array([i + [0]*(max_len6-len(i)) for i in tokenized6.values])

np.array(padded6).shape        # Dimensions of the padded variable

(4000, 120)

In [ ]:
attention_mask6 = np.where(padded6 != 0, 1, 0)
attention_mask6.shape
input_ids6 = torch.tensor(padded6)  
attention_mask6 = torch.tensor(attention_mask6)

In [ ]:
input_segments6= np.array([_get_segments3(token, max_len6)for token in tokenized6.values])

In [ ]:
token_type_ids6 = torch.tensor(input_segments6)
input_segments6 = torch.tensor(input_segments6)

In [ ]:
with torch.no_grad():
    last_hidden_states6 = model(input_ids6, attention_mask=attention_mask6, token_type_ids=input_segments6)    # <<< 600 rows only !!!

In [ ]:
features6 = last_hidden_states6[0][:,0,:].numpy()
features6

array([[-1.0968552e+00, -1.1498391e-04, -1.8097033e-01, ...,
        -1.0345995e+00,  1.3936336e-01,  5.3766835e-01],
       [-9.7731698e-01, -6.9209188e-02, -2.8442854e-01, ...,
        -1.0574378e+00,  1.5433541e-01,  5.2988535e-01],
       [-5.1702094e-01,  8.6537391e-02, -4.3555906e-01, ...,
        -1.2390417e+00,  5.0639510e-01,  6.3943839e-01],
       ...,
       [-5.3709042e-01, -2.7352095e-01, -1.2383809e-03, ...,
        -8.9592093e-01,  2.8311631e-01,  4.2431101e-01],
       [-1.0014508e+00,  2.5311509e-02, -2.9549718e-01, ...,
        -7.3728853e-01,  3.4781927e-01,  7.0129365e-01],
       [-6.0242695e-01, -2.3229939e-01, -3.0232551e-02, ...,
        -2.9623303e-01, -3.0693626e-01,  6.4687228e-01]], dtype=float32)

#**df7**

In [ ]:
pair7= df7['Title1'] + [" [SEP] "] + df7['Title2'] 
tokenized7 = pair7.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len7 = 0                 # padding all lists to the same size
for i in tokenized7.values:
    if len(i) > max_len7:
        max_len7 = len(i)

In [ ]:
max_len7=120

In [ ]:
padded7 = np.array([i + [0]*(max_len7-len(i)) for i in tokenized7.values])

np.array(padded7).shape        # Dimensions of the padded variable

(4000, 120)

In [ ]:
attention_mask7 = np.where(padded7 != 0, 1, 0)
attention_mask7.shape
input_ids7 = torch.tensor(padded7)  
attention_mask7 = torch.tensor(attention_mask7)

In [ ]:
input_segments7= np.array([_get_segments3(token, max_len7)for token in tokenized7.values])

In [ ]:
token_type_ids7 = torch.tensor(input_segments7)
input_segments7 = torch.tensor(input_segments7)

In [ ]:
with torch.no_grad():
    last_hidden_states7 = model(input_ids7, attention_mask=attention_mask7, token_type_ids=input_segments7)    # <<< 600 rows only !!!

In [ ]:
features7 = last_hidden_states7[0][:,0,:].numpy()
features7

array([[-1.2884122 ,  0.20331797, -0.50073844, ..., -0.7101118 ,
         0.02487423,  0.4270186 ],
       [-1.1560966 ,  0.2679882 , -0.35617962, ..., -0.8309484 ,
         0.04310943,  0.46193328],
       [-1.0861632 ,  0.10153062, -0.2624694 , ..., -0.92084444,
         0.07677861,  0.39786732],
       ...,
       [-0.6685464 , -0.06018602, -0.65393317, ..., -0.91511923,
         0.17649955,  0.6163837 ],
       [-0.6962306 , -0.17427117, -0.50982594, ..., -0.802863  ,
         0.0717968 ,  0.7323297 ],
       [-0.6200275 ,  0.07714535, -0.36428013, ..., -0.8783737 ,
        -0.24462415,  0.57444084]], dtype=float32)

#**df8**

In [ ]:
pair8= df8['Title1'] + [" [SEP] "] + df8['Title2'] 
tokenized8 = pair8.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len8 = 0                 # padding all lists to the same size
for i in tokenized8.values:
    if len(i) > max_len8:
        max_len8 = len(i)

In [ ]:
max_len8=120
padded8 = np.array([i + [0]*(max_len8-len(i)) for i in tokenized8.values])

np.array(padded8).shape        # Dimensions of the padded variable

(3976, 120)

In [ ]:
attention_mask8 = np.where(padded8 != 0, 1, 0)
attention_mask8.shape
input_ids8 = torch.tensor(padded8)  
attention_mask8 = torch.tensor(attention_mask8)

In [ ]:
input_segments8= np.array([_get_segments3(token, max_len8)for token in tokenized8.values])

In [ ]:
token_type_ids8 = torch.tensor(input_segments8)
input_segments8 = torch.tensor(input_segments8)

In [ ]:
with torch.no_grad():
    last_hidden_states8 = model(input_ids8, attention_mask=attention_mask8, token_type_ids=input_segments8)    # <<< 600 rows only !!!

In [ ]:
features8 = last_hidden_states8[0][:,0,:].numpy()
features8

array([[-1.1164187 ,  0.04471485, -0.74532586, ..., -0.8951335 ,
         0.21163571,  0.09688786],
       [-1.0465589 ,  0.19762649, -0.4905701 , ..., -0.7601505 ,
         0.14583972,  0.42327687],
       [-0.8697214 , -0.01018895, -0.7331715 , ..., -0.9402355 ,
         0.26161188,  0.35526732],
       ...,
       [-0.40496024, -0.18761759, -0.2590021 , ..., -1.064134  ,
         0.11511648,  0.7073144 ],
       [-0.40057147, -0.03074435, -0.18038625, ..., -0.77580166,
         0.0420424 ,  0.7634865 ],
       [-0.68973017, -0.30736685,  0.3018322 , ..., -0.79160756,
         0.01482947,  0.23705907]], dtype=float32)

#**df9**

In [ ]:
pair9= df9['Title1'] + [" [SEP] "] + df9['Title2'] 
tokenized9 = pair9.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
max_len9 = 0                 # padding all lists to the same size
for i in tokenized9.values:
    if len(i) > max_len9:
        max_len9 = len(i)

In [ ]:
max_len9=120
padded9 = np.array([i + [0]*(max_len9-len(i)) for i in tokenized9.values])

np.array(padded9).shape        # Dimensions of the padded variable

(2000, 120)

In [ ]:
attention_mask9 = np.where(padded9 != 0, 1, 0)
attention_mask9.shape
input_ids9 = torch.tensor(padded9)  
attention_mask9 = torch.tensor(attention_mask9)

In [ ]:
input_segments9= np.array([_get_segments3(token, max_len9)for token in tokenized9.values])

In [ ]:
token_type_ids9 = torch.tensor(input_segments9)
input_segments9 = torch.tensor(input_segments9)

In [ ]:
with torch.no_grad():
    last_hidden_states9 = model(input_ids9, attention_mask=attention_mask9, token_type_ids=input_segments9)    

In [ ]:
features9 = last_hidden_states9[0][:,0,:].numpy()
features9

array([[-0.22349076, -0.12304441, -0.23047546, ..., -0.7325211 ,
         0.07089544,  0.5605494 ],
       [-0.5841898 ,  0.01884044, -0.16195443, ..., -0.9090815 ,
         0.45706832,  0.61063266],
       [-0.35846508, -0.3969609 ,  0.13428313, ..., -0.59005606,
         0.27653998,  0.26065153],
       ...,
       [-0.5939225 , -0.04386819, -0.3164953 , ..., -0.86987656,
         0.25392085,  0.5906879 ],
       [-0.7364809 , -0.0380206 , -0.1034371 , ..., -0.9682361 ,
         0.30912295, -0.01217852],
       [-0.06144851,  0.20969903, -0.15128487, ..., -0.89905167,
         0.55792844,  0.31018138]], dtype=float32)

#**df10**

In [ ]:
df10.shape

(2000, 7)

In [ ]:
pair10= df10['Title1'] + [" [SEP] "] + df10['Title2'] 
tokenized10 = pair10.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=512)))

In [ ]:
pair10.shape

(2000,)

In [ ]:
max_len10 = 0                 # padding all lists to the same size
for i in tokenized10.values:
    if len(i) > max_len10:
        max_len10 = len(i)

In [ ]:
max_len10=120
padded10 = np.array([i + [0]*(max_len10-len(i)) for i in tokenized10.values])

np.array(padded10).shape        # Dimensions of the padded variable

(2000, 120)

In [ ]:
attention_mask10 = np.where(padded10 != 0, 1, 0)
attention_mask10.shape
input_ids10 = torch.tensor(padded10)  
attention_mask10 = torch.tensor(attention_mask10)

In [ ]:
input_segments10= np.array([_get_segments3(token, max_len10)for token in tokenized10.values])

In [ ]:
token_type_ids10 = torch.tensor(input_segments10)
input_segments10 = torch.tensor(input_segments10)

In [ ]:
with torch.no_grad():
    last_hidden_states10 = model(input_ids10, attention_mask=attention_mask10, token_type_ids=input_segments10)    # <<< 600 rows only !!!

In [ ]:
features10 = last_hidden_states10[0][:,0,:].numpy()
features10

#**Classification**

In [ ]:
features=np.concatenate([features3,features4,features5,features6,features7])

In [ ]:
features.shape

(6000, 768)

In [ ]:
Total = pd.concat([df3,df4,df5,df6,df7], ignore_index=True)

In [ ]:
Total

In [ ]:
labels =Total['Label']
labels

0        1
1        1
2        1
3        1
4        1
        ..
29995    0
29996    0
29997    0
29998    0
29999    0
Name: Label, Length: 30000, dtype: int64

In [ ]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels,test_size=0.2,random_state=42)

#**LogisticRegression Optimized**

---



In [ ]:
#n_splits=2
#cross_val_score=5
parameters = {'C': np.linspace(0.0001, 100, 20)}
grid_search = GridSearchCV(LogisticRegression(), parameters, cv=5)
grid_search.fit(train_features, train_labels)
print('best parameters: ', grid_search.best_params_)
print('best scrores: ', grid_search.best_score_)

best parameters:  {'C': 36.842168421052634}
best scrores:  0.8771666666666667


In [ ]:
lr_clf = LogisticRegression(C=36.84)
lr_clf.fit(train_features, train_labels)


LogisticRegression(C=36.84, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr_clf.score(test_features, test_labels)

0.8881666666666667

In [ ]:
y_predLr = lr_clf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_predLr))
print(confusion_matrix(test_labels, y_predLr))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      3005
           1       0.90      0.88      0.89      2995

    accuracy                           0.89      6000
   macro avg       0.89      0.89      0.89      6000
weighted avg       0.89      0.89      0.89      6000

[[2706  299]
 [ 372 2623]]


In [ ]:
scores = cross_val_score(lr_clf, features, labels,cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.866 (std: 0.017)



#**Decision tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf = DecisionTreeClassifier(max_depth = 100, random_state = 0,criterion='gainracue')

In [ ]:
clf.fit(train_features, train_labels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=100, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
y_preddt = clf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_preddt))
print(confusion_matrix(test_labels, y_preddt))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79      3005
           1       0.78      0.79      0.79      2995

    accuracy                           0.79      6000
   macro avg       0.79      0.79      0.79      6000
weighted avg       0.79      0.79      0.79      6000

[[2343  662]
 [ 614 2381]]


In [ ]:
# Predict for 1 observation
clf.predict(test_features)
# Predict for multiple observations
#clf.predict(test_features[0:200])

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
# The score method returns the accuracy of the model
score = clf.score(test_features, test_labels)
print(score)

0.8098333333333333


In [ ]:
scores = cross_val_score(clf, features, labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.774 (std: 0.019)



#**SVM**

In [ ]:
from sklearn.svm import SVC

In [ ]:

svclassifier = SVC(kernel='linear')
svclassifier.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[2767  238]
 [ 396 2599]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90      3005
           1       0.92      0.87      0.89      2995

    accuracy                           0.89      6000
   macro avg       0.90      0.89      0.89      6000
weighted avg       0.90      0.89      0.89      6000



In [ ]:
param_grid = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=15.0min
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 15.0min remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.8min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.9min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.6min
[CV] C=1, gamma=1, kernel=rbf ........................................


In [ ]:
grid.best_params_

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

#Cross_Val

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn import svm

In [ ]:
clf = svm.SVC(kernel='linear')

In [ ]:
scores = cross_val_score(clf, test_labels, y_pred, cv=5)

In [ ]:
scores = cross_val_score(clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.850 (std: 0.011)



#**MLP Best params**

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=100)
from sklearn.datasets import make_classification

In [ ]:
parameter_space = {
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(train_features, train_labels)

GridSearchCV(cv=3, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=100, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state...
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'activation': ['ta

In [ ]:
# Best paramete set
print('Best parameters found:\n', clf.best_params_)

# All results
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))


Best parameters found:
 {'activation': 'tanh', 'alpha': 0.05, 'hidden_layer_sizes': (100,), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.878 (+/-0.004) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.876 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'adam'}
0.877 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.876 (+/-0.005) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.878 (+/-0.004) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.874 (+/-0.006) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'adam'

In [ ]:
y_true, y_pred = test_labels , clf.predict(test_features)

from sklearn.metrics import classification_report, confusion_matrix
print('Results on the test set:')
print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

Results on the test set:
              precision    recall  f1-score   support

           0       0.90      0.89      0.90      3005
           1       0.89      0.91      0.90      2995

    accuracy                           0.90      6000
   macro avg       0.90      0.90      0.90      6000
weighted avg       0.90      0.90      0.90      6000

[[2667  338]
 [ 280 2715]]


In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(train_features, train_labels)
clf.predict_proba(test_features[:1])

array([[1.51787609e-08, 9.99999985e-01]])

In [ ]:
clf.predict(test_features[:1000, :])

In [ ]:
clf.score(test_features, test_labels)

0.8841666666666667

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
clf = MLPClassifier.mlp(kernel='linear')

In [ ]:
scores = cross_val_score(clf, test_labels, y_pred, cv=5)

In [ ]:

scores = cross_val_score(clf, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.872 (std: 0.014)



#**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=20, random_state=0)
rf.fit(train_features, train_labels)
y_pred1 = rf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred1))
print(confusion_matrix(test_labels, y_pred1))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      3005
           1       0.90      0.82      0.86      2995

    accuracy                           0.86      6000
   macro avg       0.87      0.86      0.86      6000
weighted avg       0.87      0.86      0.86      6000

[[2729  276]
 [ 540 2455]]


In [ ]:
scores = cross_val_score(rf, features, labels, cv=5)

KeyboardInterrupt: ignored

In [ ]:
scores = cross_val_score(rf, test_features, test_labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.856 (std: 0.006)



#**Naive Bayes**

#Gaussian

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_features, train_labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(test_features)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(test_labels, y_pred))

Accuracy: 0.8358333333333333


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred))
print(confusion_matrix(test_labels, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84      3005
           1       0.83      0.84      0.84      2995

    accuracy                           0.84      6000
   macro avg       0.84      0.84      0.84      6000
weighted avg       0.84      0.84      0.84      6000

[[2495  510]
 [ 475 2520]]


*Cross Validation*

In [ ]:
scores = cross_val_score(gnb, test_labels, y_pred, cv=5)
scores = cross_val_score(gnb, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.836 (std: 0.011)



#**Optimized SVC**

In [ ]:
from sklearn.svm import SVC

In [ ]:
model = SVC()

In [ ]:
model.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction = model.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,prediction))
print(confusion_matrix(test_labels, prediction))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89      3005
           1       0.93      0.84      0.88      2995

    accuracy                           0.89      6000
   macro avg       0.89      0.89      0.89      6000
weighted avg       0.89      0.89      0.89      6000

[[2819  186]
 [ 479 2516]]


In [ ]:
param_grid = {'C':[1,10],'gamma':[1,0.1], 'kernel':['linear','rbf']}


In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=14.7min
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 14.7min remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=14.4min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=14.5min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=14.5min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=14.3min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=24.0min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=24.0min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=24.1min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] .

In [ ]:
grid.best_params_

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90       587
           1       0.95      0.85      0.90       613

    accuracy                           0.90      1200
   macro avg       0.91      0.90      0.90      1200
weighted avg       0.91      0.90      0.90      1200

[[558  29]
 [ 89 524]]


#**Random Forest Optimized**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(random_state=42)

In [ ]:
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [ ]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(train_features, train_labels)

In [ ]:
CV_rfc.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'max_features': 'auto',
 'n_estimators': 500}

In [ ]:
rfc1=RandomForestClassifier(random_state=42, max_features='auto', n_estimators= 200, max_depth=8, criterion='gini')

In [ ]:
rfc1.fit(train_features, train_labels)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:

pred=rfc1.predict(test_features)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy for Random Forest on CV data: ",accuracy_score(test_labels,pred))

Accuracy for Random Forest on CV data:  0.8441666666666666


#**XGBoost**

In [ ]:
import xgboost as xgb
modelxgb=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
modelxgb.fit(train_features, train_labels)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
predxgb = modelxgb.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,predxgb))
print(confusion_matrix(test_labels, predxgb))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85      3005
           1       0.88      0.81      0.84      2995

    accuracy                           0.85      6000
   macro avg       0.85      0.85      0.85      6000
weighted avg       0.85      0.85      0.85      6000

[[2665  340]
 [ 578 2417]]


In [ ]:
model.score(test_features,test_labels)


0.847

In [ ]:
scores = cross_val_score(model, test_labels, test_features, cv=5)

In [ ]:
scores = cross_val_score(model, test_features, test_labels, cv=10)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.847 (std: 0.012)



#**Optimized DT**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Same 3-step process

# 1. Instantiate
# default criterion=gini
# you can swap to criterion=entropy 
dtc = DecisionTreeClassifier(random_state=0)

# 2. Fit
dtc.fit(train_features, train_labels)

# 3. Predict, there're 4 features in the iris dataset
y_pred_class = dtc.predict(test_features)

In [ ]:
from sklearn import metrics

In [ ]:
# Accuracy
metrics.accuracy_score(test_labels, y_pred_class)

0.7873333333333333

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred_class))
print(confusion_matrix(test_labels, y_pred_class))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79      3005
           1       0.78      0.79      0.79      2995

    accuracy                           0.79      6000
   macro avg       0.79      0.79      0.79      6000
weighted avg       0.79      0.79      0.79      6000

[[2343  662]
 [ 614 2381]]


In [ ]:
# Import
from sklearn.model_selection import GridSearchCV

# Define the parameter values that should be searched
sample_split_range = list(range(1, 50))

# Create a parameter grid: map the parameter names to the values that should be searched
# Simply a python dictionary
# Key: parameter name
# Value: list of values that should be searched for that parameter
# Single key-value pair for param_grid
param_grid = dict(min_samples_split=sample_split_range)

# instantiate the grid
grid = GridSearchCV(dtc, param_grid, cv=10, scoring='accuracy')

# fit the grid with data
grid.fit(train_features, train_labels)

In [ ]:

# Single best score achieved across all params (min_samples_split)
print(grid.best_score_)

# Dictionary containing the parameters (min_samples_split) used to generate that score
print(grid.best_params_)

# Actual model object fit with those best parameters
# Shows default parameters that we did not specify
print(grid.best_estimator_)

In [ ]:
# Entropy of child 1 = 0
# Perfect split for this child

# Entropy of child 2 = 0.918
-(2/3)*np.log2(2/3) - (1/3)*np.log2(1/3)

In [ ]:
# Weighted average of entropy(children)
(3/4)*(0.9184) + (1/4)*0

In [ ]:
# Entropy Gain
1 - (3/4)*(0.9184) + (1/4)*0