##**Installing the transformers library**



In [ ]:
!pip install transformers

     |████████████████████████████████| 2.0MB 5.3MB/s 
     |████████████████████████████████| 890kB 17.4MB/s 
     |████████████████████████████████| 3.2MB 30.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp37-none-any.whl size=893262 sha256=50d908017487f140c6bf9848d02b23744368350242f6f06f9fd6549d6e3ac148
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
import random
import time

l = range(100000)

tps1 = time.clock()
random.shuffle(l)
l.sort()
tps2 = time.clock()
print(tps2 - tps1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


TypeError: ignored

##**Importing the tools**

In [ ]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
import re
warnings.filterwarnings('ignore')

##**Importing the dataset from Drive**

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
df=pd.read_csv('gdrive/My Drive/Total_cleaned.csv',delimiter=';')

In [ ]:
df1=pd.read_csv('gdrive/My Drive/Final_DUP.csv',delimiter=';')

In [ ]:
df2=pd.read_csv('gdrive/My Drive/Final_NDUP.csv',delimiter=';')

In [ ]:
#Mozilla
df1=pd.read_csv('gdrive/My Drive/cln_copie_dup_total1.csv',delimiter=';')
df2=pd.read_csv('gdrive/My Drive/cln_copie_nndup_total1.csv',delimiter=';')

In [ ]:
df1=pd.read_csv('gdrive/My Drive/test_dup_TB.csv',delimiter=';')
df2=pd.read_csv('gdrive/My Drive/test_Nondup_TB.csv',delimiter=';')

In [ ]:
df1=pd.read_csv('gdrive/My Drive/EP_test_dup.csv',delimiter=';')
df2=pd.read_csv('gdrive/My Drive/EP_test_nondup.csv',delimiter=';')

In [ ]:
Tdf1=pd.read_csv('gdrive/My Drive/test_dup_TB.csv',delimiter=';')
Tdf2=pd.read_csv('gdrive/My Drive/test_Nondup_TB.csv',delimiter=';')

In [ ]:
df1['Label'] = 1
df2['Label'] = 0

In [ ]:
Tdf1['Label'] = 1
Tdf2['Label'] = 0
df1

##**Loading the Pre-trained BERT model**

In [ ]:
import time
start = time.time()
model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)



##**Lower case**

In [ ]:
df[0]= df[0].str.lower()
df[1]= df[1].str.lower()
df[2]= df[2].str.lower()
df[3]= df[3].str.lower()
df[4]= df[4].str.lower()
df[5]= df[5].str.lower()

## **Remove Digits**

In [ ]:
df[3] = df[3].str.replace(r'0', '')
df[3] = df[3].str.replace(r'1', '')
df[3] = df[3].str.replace(r'2', '')
df[3] = df[3].str.replace(r'3', '')
df[3] = df[3].str.replace(r'4', '')
df[3] = df[3].str.replace(r'5', '')
df[3] = df[3].str.replace(r'6', '')
df[3] = df[3].str.replace(r'7', '')
df[3] = df[3].str.replace(r'8', '')
df[3] = df[3].str.replace(r'9', '')

##**Remove special characters**

In [ ]:
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r'@ ?', '')
df[3] = df[3].str.replace(r'!', '')
df[3] = df[3].str.replace(r'+', '')
df[3] = df[3].str.replace(r'-', '')
df[3] = df[3].str.replace(r'/', '')
df[3] = df[3].str.replace(r':', '')
df[3] = df[3].str.replace(r';', '')
df[3] = df[3].str.replace(r'>', '')
df[3] = df[3].str.replace(r'=', '')
df[3] = df[3].str.replace(r'<', '')
df[3] = df[3].str.replace(r'(', '')
df[3] = df[3].str.replace(r')', '')
df[3] = df[3].str.replace(r'#', '')
df[3] = df[3].str.replace(r'$', '')
df[3] = df[3].str.replace(r'&', '')
df[3] = df[3].str.replace(r'*', '')
df[3] = df[3].str.replace(r'%', '')
df[3] = df[3].str.replace(r'_', '')

In [ ]:
df2.shape

(17005, 7)

##**Convert to String type**

In [ ]:
df[3] = pd.Series(df[3], dtype="string")  # Pblm tokenize : " Input is not valid ,Should be a string, a list/tuple of strings or a list/tuple of integers"
df[2] = pd.Series(df[2], dtype="string")
df[2] = df[2].astype("|S")
df[2].str.decode("utf-8")
df[3] = df[3].astype("|S")
df[3].str.decode("utf-8")

In [ ]:
df[3].str.len()


##**Tokenization**

In [ ]:
batch_31=df1[:3000]
batch_32=df2[:3000]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[3000:6000]
batch_42=df2[3000:6000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[6000:9000]
batch_52=df2[6000:9000]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[9000:12000]
batch_62=df2[9000:12000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[12000:15000]
batch_72=df2[12000:15000]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[15000:18000]
batch_82=df2[15000:18000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[18000:21000]
batch_92=df2[18000:21000]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[21000:]
batch_102=df2[21000:]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)

#**Batch ThunderBird**

In [ ]:
batch_31=df1[:500]
batch_32=df2[:500]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[500:1000]
batch_42=df2[500:1000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[1000:1500]
batch_52=df2[1000:1500]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[1500:2000]
batch_62=df2[1500:2000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[2000:2500]
batch_72=df2[2000:2500]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[2500:3000]
batch_82=df2[2500:3000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[3000:3500]
batch_92=df2[3000:3500]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[3500:4000]
batch_102=df2[3500:4000]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)
batch_111=df1[4000:]
batch_112=df2[4000:4500]
df11 = pd.concat([batch_111,batch_112], ignore_index=True)
df12 = df2[4500:5500]
df13=df2[5500:6000]
df14=df2[6000:6500]
df15=df2[6500:7000]
df16=df2[7000:7500]
df17=df2[7500:8000]
df18=df2[8000:8500]
df19=df2[8500:9000]
df20=df2[9000:9500]
df21=df2[9500:]

In [ ]:
batch_121=df1[4500:]
batch_122=df2[4500:5500]
df12 = pd.concat([batch_121,batch_122], ignore_index=True)

#**Batch EP**

In [ ]:
batch_31=df1[:500]
batch_32=df2[:500]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[500:1000]
batch_42=df2[500:1000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[1000:1500]
batch_52=df2[1000:1500]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[1500:2000]
batch_62=df2[1500:2000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[2000:2500]
batch_72=df2[2000:2500]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[2500:3000]
batch_82=df2[2500:3000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[3000:3500]
batch_92=df2[3000:3500]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[3500:4000]
batch_102=df2[3500:4000]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)
batch_111=df1[4000:4500]
batch_112=df2[4000:4500]
df11 = pd.concat([batch_111,batch_112], ignore_index=True)
batch_121=df1[4500:5000]
batch_122=df2[4500:5000]
df12 = pd.concat([batch_121,batch_122], ignore_index=True)
batch_131=df1[5000:5250]
batch_132=df2[5000:5250]
df13 = pd.concat([batch_131,batch_132], ignore_index=True)
batch_141=df1[5250:5500]
batch_142=df2[5250:5500]
df14 = pd.concat([batch_141,batch_142], ignore_index=True)
batch_151=df1[5500:5750]
batch_152=df2[5500:5750]
df15 = pd.concat([batch_151,batch_152], ignore_index=True)
batch_161=df1[5750:6000]
batch_162=df2[5750:6000]
df16 = pd.concat([batch_161,batch_162], ignore_index=True)
batch_171=df1[6000:6250]
batch_172=df2[6000:6250]
df17 = pd.concat([batch_171,batch_172], ignore_index=True)
batch_181=df1[6250:6500]
batch_182=df2[6250:6500]
df18 = pd.concat([batch_181,batch_182], ignore_index=True)
batch_191=df1[6500:6750]
batch_192=df2[6500:6750]
df19 = pd.concat([batch_191,batch_192], ignore_index=True)
batch_201=df1[6750:7000]
batch_202=df2[6750:7000]
df20 = pd.concat([batch_201,batch_202], ignore_index=True)
batch_211=df1[7000:7250]
batch_212=df2[7000:7250]
df21 = pd.concat([batch_211,batch_212], ignore_index=True)
batch_221=df1[7250:7500]
batch_222=df2[7250:7500]
df22 = pd.concat([batch_221,batch_222], ignore_index=True)
batch_231=df1[7500:7750]
batch_232=df2[7500:7750]
df23 = pd.concat([batch_231,batch_232], ignore_index=True)
batch_241=df1[7750:8000]
batch_242=df2[7750:8000]
df24 = pd.concat([batch_241,batch_242], ignore_index=True)
batch_251=df1[8000:8250]
batch_252=df2[8000:8250]
df25 = pd.concat([batch_251,batch_252], ignore_index=True)
batch_261=df1[8250:8500]
batch_262=df2[8250:8500]
df26 = pd.concat([batch_261,batch_262], ignore_index=True)
batch_271=df1[8500:8750]
batch_272=df2[8500:8750]
df27 = pd.concat([batch_271,batch_272], ignore_index=True)
batch_281=df1[8750:9000]
batch_282=df2[8750:9000]
df28 = pd.concat([batch_281,batch_282], ignore_index=True)
batch_291=df1[9000:9250]
batch_292=df2[9000:9250]
df29 = pd.concat([batch_291,batch_292], ignore_index=True)
batch_301=df1[9250:9500]
batch_302=df2[9250:9500]
df30 = pd.concat([batch_301,batch_302], ignore_index=True)
batch_311=df1[9500:9750]
batch_312=df2[9500:9750]
df31 = pd.concat([batch_311,batch_312], ignore_index=True)
batch_321=df1[9750:10000]
batch_322=df2[9750:10000]
df32 = pd.concat([batch_321,batch_322], ignore_index=True)

#**Batch CrossProject**

In [ ]:
batch_31=df1[:500]
batch_32=df2[:500]
df3 = pd.concat([batch_31,batch_32], ignore_index=True)
batch_41=df1[500:1000]
batch_42=df2[500:1000]
df4 = pd.concat([batch_41,batch_42], ignore_index=True)
batch_51=df1[1000:1500]
batch_52=df2[1000:1500]
df5 = pd.concat([batch_51,batch_52], ignore_index=True)
batch_61=df1[1500:2000]
batch_62=df2[1500:2000]
df6 = pd.concat([batch_61,batch_62], ignore_index=True)
batch_71=df1[2000:2500]
batch_72=df2[2000:2500]
df7 = pd.concat([batch_71,batch_72], ignore_index=True)
batch_81=df1[2500:3000]
batch_82=df2[2500:3000]
df8 = pd.concat([batch_81,batch_82], ignore_index=True)
batch_91=df1[3000:3500]
batch_92=df2[3000:3500]
df9 = pd.concat([batch_91,batch_92], ignore_index=True)
batch_101=df1[3500:4000]
batch_102=df2[3500:4000]
df10 = pd.concat([batch_101,batch_102], ignore_index=True)
batch_111=df1[4000:4500]
batch_112=df2[4000:4500]
df11 = pd.concat([batch_111,batch_112], ignore_index=True)
batch_121=df1[4500:5000]
batch_122=df2[4500:5000]
df12 = pd.concat([batch_121,batch_122], ignore_index=True)
batch_311=df1[5000:5250]
batch_312=df2[5000:5250]
df31 = pd.concat([batch_311,batch_312], ignore_index=True)
batch_321=df1[5250:5500]
batch_322=df2[5250:5500]
df32 = pd.concat([batch_321,batch_322], ignore_index=True)
batch_131=Tdf1[:250]
batch_132=Tdf2[:250]
df13 = pd.concat([batch_131,batch_132], ignore_index=True)
batch_141=Tdf1[250:500]
batch_142=Tdf2[250:500]
df14 = pd.concat([batch_141,batch_142], ignore_index=True)
batch_151=Tdf1[500:750]
batch_152=Tdf2[500:750]
df15 = pd.concat([batch_151,batch_152], ignore_index=True)
batch_161=Tdf1[750:1000]
batch_162=Tdf2[750:1000]
df16 = pd.concat([batch_161,batch_162], ignore_index=True)
batch_171=Tdf1[1000:1250]
batch_172=Tdf2[1000:1250]
df17 = pd.concat([batch_171,batch_172], ignore_index=True)
batch_181=Tdf1[1250:1500]
batch_182=Tdf2[1250:1500]
df18 = pd.concat([batch_181,batch_182], ignore_index=True)
batch_191=Tdf1[1500:1750]
batch_192=Tdf2[1500:1750]
df19 = pd.concat([batch_191,batch_192], ignore_index=True)
batch_201=Tdf1[1750:2000]
batch_202=Tdf2[1750:2000]
df20 = pd.concat([batch_201,batch_202], ignore_index=True)
batch_211=Tdf1[2000:2250]
batch_212=Tdf2[2000:2250]
df21 = pd.concat([batch_211,batch_212], ignore_index=True)
batch_221=Tdf1[2250:2500]
batch_222=Tdf2[2250:2500]
df22 = pd.concat([batch_221,batch_222], ignore_index=True)
batch_231=Tdf1[2500:2750]
batch_232=Tdf2[2500:2750]
df23 = pd.concat([batch_231,batch_232], ignore_index=True)
batch_241=Tdf1[2750:3000]
batch_242=Tdf2[2750:3000]
df24 = pd.concat([batch_241,batch_242], ignore_index=True)
batch_251=Tdf1[3000:3250]
batch_252=Tdf2[3000:3250]
df25 = pd.concat([batch_251,batch_252], ignore_index=True)
batch_261=Tdf1[3250:3500]
batch_262=Tdf2[3250:3500]
df26 = pd.concat([batch_261,batch_262], ignore_index=True)
batch_271=Tdf1[3500:3750]
batch_272=Tdf2[3500:3750]
df27 = pd.concat([batch_271,batch_272], ignore_index=True)
batch_281=Tdf1[3750:4000]
batch_282=Tdf2[3750:4000]
df28 = pd.concat([batch_281,batch_282], ignore_index=True)
batch_291=Tdf1[4000:4250]
batch_292=Tdf2[4000:4250]
df29 = pd.concat([batch_291,batch_292], ignore_index=True)
batch_301=Tdf1[4250:4500]
batch_302=Tdf2[4250:4500]
df30 = pd.concat([batch_301,batch_302], ignore_index=True)




In [ ]:
def _get_segments3(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    if len(tokens)>max_seq_length:
        raise IndexError("Token length more than max seq length!")
    segments = []
    first_sep = False
    current_segment_id = 0 
    for token in tokens:
        segments.append(current_segment_id)
        #print(token)
        if token == 102:
            #if first_sep:
                #first_sep = False 
            #else:
           current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

#**df3**

In [ ]:
pair3= df3['Title1'] + [" [SEP] "] + df3['Title2']
tokenized3 = pair3.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair3[500]

'usability issue with external editors geirl [SEP] api deleted field idebuguiconstants.imgactsynced'

In [ ]:
pair3= df3['Title1'] + df3['Description1']+ [" [SEP] "] + df3['Title2'] + df3['Description2']
tokenized3 = pair3.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
tokenizer.tokenize('mozilla menubar reappears when no open windows thunderbird similar to bug ')

In [ ]:
tokenizer.tokenize('need to be able to create a new repo connection from the selection dialog gcxeits very awkward that you cannot create a new repository connection when you go  to associate a project with a repo.')

In [ ]:
tokenized3[1]

In [ ]:
max_len3 = 0                 # padding all lists to the same size
for i in tokenized3.values:
    if len(i) > max_len3:
        max_len3 = len(i)
max_len3 =400
padded3 = np.array([i + [0]*(max_len3-len(i)) for i in tokenized3.values])

np.array(padded3).shape         

(1000, 400)

In [ ]:
attention_mask3 = np.where(padded3 != 0, 1, 0)
attention_mask3.shape
input_ids3 = torch.tensor(padded3)  
attention_mask3 = torch.tensor(attention_mask3)
input_segments3= np.array([_get_segments3(token, max_len3)for token in tokenized3.values])
token_type_ids3 = torch.tensor(input_segments3)
input_segments3 = torch.tensor(input_segments3)

In [ ]:
with torch.no_grad():
    last_hidden_states3 = model(input_ids3, attention_mask=attention_mask3, token_type_ids=input_segments3)    # <<< 600 rows only !!!
features3 = last_hidden_states3[0][:,0,:].numpy()
features3    

array([[-1.174114  , -0.09349257, -0.29868576, ..., -0.881565  ,
         0.0985333 ,  0.30534974],
       [-0.7552414 , -0.14569645, -0.56042576, ..., -0.8465867 ,
         0.30912575,  0.582005  ],
       [-0.6472141 , -0.07355616, -0.25476506, ..., -0.90402377,
         0.43055063,  0.1609221 ],
       ...,
       [-0.36480492, -0.14358969,  0.18249223, ..., -0.4958595 ,
        -0.43827295,  0.5061376 ],
       [-0.632436  , -0.32667625,  0.28313512, ..., -0.4099592 ,
        -0.06551511,  0.37699252],
       [-0.67632914, -0.33627635,  0.07468707, ..., -0.79508424,
         0.17976522,  0.6531499 ]], dtype=float32)

#**df4**

In [ ]:
pair4=df4['Title1'] + df4['Description1']+ [" [SEP] "] + df4['Title2']  + df4['Description2']
tokenized4 = pair4.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
#pair4=df4['Description1'] + [" [SEP] "] + df4['Description2']
pair4= df4['Title1'] + [" [SEP] "] + df4['Title2'] 
tokenized4 = pair4.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len4 = 0                 # padding all lists to the same size
for i in tokenized4.values:
    if len(i) > max_len4:
        max_len4 = len(i)
max_len4 =400
padded4 = np.array([i + [0]*(max_len4-len(i)) for i in tokenized4.values])

np.array(padded4).shape          

(1000, 400)

In [ ]:
attention_mask4 = np.where(padded4 != 0, 1, 0)
attention_mask4.shape
input_ids4 = torch.tensor(padded4)  
attention_mask4 = torch.tensor(attention_mask4)
input_segments4= np.array([_get_segments3(token, max_len4)for token in tokenized4.values])
token_type_ids4 = torch.tensor(input_segments4)
input_segments4 = torch.tensor(input_segments4)

In [ ]:
with torch.no_grad():
    last_hidden_states4 = model(input_ids4, attention_mask=attention_mask4, token_type_ids=input_segments4)   
features4 = last_hidden_states4[0][:,0,:].numpy()
features4    

array([[-0.8656477 , -0.00970127, -0.49029198, ..., -0.7175869 ,
         0.622179  ,  0.3734092 ],
       [-0.8712847 , -0.29619402, -0.3538372 , ..., -0.8126364 ,
         0.03289595,  0.72704345],
       [-0.4169303 ,  0.28583857, -0.5328667 , ..., -1.1660382 ,
         0.54393077,  0.35814762],
       ...,
       [-0.5317749 , -0.45388013, -0.45984524, ..., -0.75945854,
        -0.26530027,  0.647243  ],
       [-0.87570804, -0.66838884, -0.22412717, ..., -0.81014645,
        -0.33118105,  0.44196242],
       [-0.9421244 , -0.27575123,  0.15507278, ..., -1.1286151 ,
        -0.40861472,  0.57805747]], dtype=float32)

#**df5**

In [ ]:
pair5= df5['Title1'] + [" [SEP] "] + df5['Title2'] 

In [ ]:
#pair5=df5['Title1'] + df5['Description1']+ [" [SEP] "] + df5['Title2'] + df5['Description2']
tokenized5 = pair5.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

##**Padding**

In [ ]:
max_len5 = 0                 # padding all lists to the same size
for i in tokenized5.values:
    if len(i) > max_len5:
        max_len5 = len(i)

In [ ]:
max_len5 =400
padded5 = np.array([i + [0]*(max_len5-len(i)) for i in tokenized5.values])

np.array(padded5).shape        # Dimensions of the padded variable

(1000, 400)

##**Masking**

In [ ]:
attention_mask5 = np.where(padded5 != 0, 1, 0)
attention_mask5.shape
input_ids5 = torch.tensor(padded5)  
attention_mask5 = torch.tensor(attention_mask5)

In [ ]:
input_ids5[0] ######## TITLE 2

##**Running the `model()` function through BERT**

In [ ]:
input_segments5= np.array([_get_segments3(token, max_len5)for token in tokenized5.values])
token_type_ids5 = torch.tensor(input_segments5)
input_segments5 = torch.tensor(input_segments5)

In [ ]:
with torch.no_grad():
    last_hidden_states5 = model(input_ids5, attention_mask=attention_mask5, token_type_ids=input_segments5)    # <<< 600 rows only !!!

##**Slicing the part of the output of BERT : [cls]**

In [ ]:
features5 = last_hidden_states5[0][:,0,:].numpy()
features5

array([[-0.9109517 , -0.05337676, -0.30842942, ..., -0.9966682 ,
         0.15199827,  0.20217219],
       [-0.5676509 ,  0.08843943, -0.53601766, ..., -0.85545015,
        -0.15221041,  0.53532195],
       [-0.7333576 ,  0.16832514, -0.6566877 , ..., -0.8630595 ,
         0.16315794,  0.5281783 ],
       ...,
       [-0.40766877, -0.21933368, -0.41889548, ..., -0.5808763 ,
        -0.18957634,  0.16838819],
       [-0.37387365,  0.03596697, -0.3334533 , ..., -0.7031258 ,
         0.30394775,  0.33992624],
       [-0.7778313 , -0.11517528, -0.38509133, ..., -0.6621039 ,
        -0.2333609 ,  0.9779239 ]], dtype=float32)

#**df6**

In [ ]:
pair6=df6['Title1'] + df6['Description1']+ [" [SEP] "] + df6['Title2'] + df6['Description2']
tokenized6 = pair6.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair6= df6['Title1'] + [" [SEP] "] + df6['Title2'] 
tokenized6 = pair6.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len6 = 0                 # padding all lists to the same size
for i in tokenized6.values:
    if len(i) > max_len6:
        max_len6 = len(i)

In [ ]:
max_len6=400
padded6 = np.array([i + [0]*(max_len6-len(i)) for i in tokenized6.values])

np.array(padded6).shape        # Dimensions of the padded variable

(1000, 400)

In [ ]:
attention_mask6 = np.where(padded6 != 0, 1, 0)
attention_mask6.shape
input_ids6 = torch.tensor(padded6)  
attention_mask6 = torch.tensor(attention_mask6)
input_segments6= np.array([_get_segments3(token, max_len6)for token in tokenized6.values])
token_type_ids6 = torch.tensor(input_segments6)
input_segments6 = torch.tensor(input_segments6)

In [ ]:
with torch.no_grad():
    last_hidden_states6 = model(input_ids6, attention_mask=attention_mask6, token_type_ids=input_segments6)   
features6 = last_hidden_states6[0][:,0,:].numpy()
features6    

array([[-0.8590334 , -0.18879086, -0.33063623, ..., -0.9019106 ,
        -0.2298854 ,  0.6351891 ],
       [-1.0722488 ,  0.25811875, -0.25732252, ..., -1.0597683 ,
        -0.3447055 ,  0.3159902 ],
       [-0.67446715,  0.11812688, -0.7099202 , ..., -0.5441661 ,
         0.00539993,  0.4780062 ],
       ...,
       [-0.4671028 , -0.4085527 , -0.7276975 , ..., -0.59182763,
         0.06320898,  0.6682286 ],
       [ 0.20505193, -0.3657541 ,  0.01371418, ..., -0.48215765,
        -0.5725326 ,  0.48162466],
       [-0.594199  ,  0.1531669 , -0.49741563, ..., -0.64179957,
        -0.07233959,  0.59847546]], dtype=float32)

#**df7**

In [ ]:
pair7=df7['Title1'] + df7['Description1']+ [" [SEP] "] + df7['Title2'] + df7['Description2']
tokenized7 = pair7.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair7= df7['Title1'] + [" [SEP] "] + df7['Title2'] 
tokenized7 = pair7.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len7 = 0                 # padding all lists to the same size
for i in tokenized7.values:
    if len(i) > max_len7:
        max_len7 = len(i)

In [ ]:
max_len7=400
padded7 = np.array([i + [0]*(max_len7-len(i)) for i in tokenized7.values])

np.array(padded7).shape        # Dimensions of the padded variable

(1000, 400)

In [ ]:
attention_mask7 = np.where(padded7 != 0, 1, 0)
attention_mask7.shape
input_ids7 = torch.tensor(padded7)  
attention_mask7 = torch.tensor(attention_mask7)
input_segments7= np.array([_get_segments3(token, max_len7)for token in tokenized7.values])
token_type_ids7 = torch.tensor(input_segments7)
input_segments7 = torch.tensor(input_segments7)

In [ ]:
with torch.no_grad():
    last_hidden_states7 = model(input_ids7, attention_mask=attention_mask7, token_type_ids=input_segments7)  
features7 = last_hidden_states7[0][:,0,:].numpy()
features7    

array([[-9.2556047e-01, -4.3795571e-02, -3.4207690e-01, ...,
        -7.2058558e-01,  4.2884666e-01,  2.4559234e-01],
       [-1.0468092e+00,  1.5520828e-04, -4.5980012e-01, ...,
        -8.3394605e-01,  2.9609305e-01,  1.0862186e-01],
       [-7.9911917e-01,  5.2310258e-01, -4.0929189e-01, ...,
        -7.8842413e-01,  5.3693914e-01,  2.2631209e-01],
       ...,
       [-3.0290264e-01, -2.4648634e-01, -1.2106145e-01, ...,
        -3.2957569e-01, -2.0467913e-01,  3.8593084e-01],
       [-6.6347963e-01, -2.8154373e-01, -6.3991433e-01, ...,
        -7.2239250e-01, -3.1349841e-01,  8.3614033e-01],
       [-8.2867950e-01, -3.5713333e-01, -3.5844898e-01, ...,
        -8.0786616e-01, -1.1812029e-01,  5.2122504e-01]], dtype=float32)

#**df8**

In [ ]:
pair8=df8['Title1'] + df8['Description1']+ [" [SEP] "] + df8['Title2'] + df8['Description2']
tokenized8 = pair8.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair8= df8['Title1'] + [" [SEP] "] + df8['Title2'] 
tokenized8 = pair8.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len8 = 0                 # padding all lists to the same size
for i in tokenized8.values:
    if len(i) > max_len8:
        max_len8 = len(i)
max_len8=400
padded8 = np.array([i + [0]*(max_len8-len(i)) for i in tokenized8.values])

np.array(padded8).shape        # Dimensions of the padded variable        

(1000, 400)

In [ ]:
attention_mask8 = np.where(padded8 != 0, 1, 0)
attention_mask8.shape
input_ids8 = torch.tensor(padded8)  
attention_mask8 = torch.tensor(attention_mask8)
input_segments8= np.array([_get_segments3(token, max_len8)for token in tokenized8.values])
token_type_ids8 = torch.tensor(input_segments8)
input_segments8 = torch.tensor(input_segments8)

In [ ]:
with torch.no_grad():
    last_hidden_states8 = model(input_ids8, attention_mask=attention_mask8, token_type_ids=input_segments8)   
features8 = last_hidden_states8[0][:,0,:].numpy()
features8    

array([[-0.56349534,  0.12034978, -0.1568485 , ..., -0.8122388 ,
         0.01709361,  0.48687583],
       [-0.73153484,  0.0923871 , -0.6039868 , ..., -0.5032317 ,
         0.27170032,  0.7797768 ],
       [-1.2171761 ,  0.04116656, -0.9760702 , ..., -1.0972648 ,
         0.19767348,  0.36149913],
       ...,
       [-0.26741895,  0.08058222, -0.10467326, ..., -0.5608201 ,
         0.29190663,  0.55572474],
       [-0.67041564, -0.21445572, -0.6257497 , ..., -0.6792196 ,
        -0.39215675,  0.7657585 ],
       [-1.3527128 , -0.30971175, -0.91651917, ..., -1.0552584 ,
        -0.09032855,  0.40051973]], dtype=float32)

#**df9**

In [ ]:
pair9=df9['Title1'] + df9['Description1']+ [" [SEP] "] + df9['Title2'] + df9['Description2']
tokenized9 = pair9.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair9= df9['Title1'] + [" [SEP] "] + df9['Title2'] 
tokenized9 = pair9.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len9 = 0                 # padding all lists to the same size
for i in tokenized9.values:
    if len(i) > max_len9:
        max_len9 = len(i)
max_len9=400
padded9 = np.array([i + [0]*(max_len9-len(i)) for i in tokenized9.values])

np.array(padded9).shape        # Dimensions of the padded variable        

(1000, 400)

In [ ]:
attention_mask9 = np.where(padded9 != 0, 1, 0)
attention_mask9.shape
input_ids9 = torch.tensor(padded9)  
attention_mask9 = torch.tensor(attention_mask9)
input_segments9= np.array([_get_segments3(token, max_len9)for token in tokenized9.values])
token_type_ids9 = torch.tensor(input_segments9)
input_segments9 = torch.tensor(input_segments9)

In [ ]:
with torch.no_grad():
    last_hidden_states9 = model(input_ids9, attention_mask=attention_mask9, token_type_ids=input_segments9)    
features9 = last_hidden_states9[0][:,0,:].numpy()
features9

array([[-0.7763251 , -0.03759931, -0.29618803, ..., -0.8825539 ,
         0.13027744,  0.7347582 ],
       [-0.8810816 , -0.15537694, -0.51778316, ..., -0.78478754,
        -0.13720514,  0.72251314],
       [-0.776736  ,  0.46823013, -0.58106506, ..., -0.66718924,
         0.07509929,  0.5049237 ],
       ...,
       [-0.76902544, -0.22509648, -0.56642956, ..., -0.7892314 ,
        -0.00800062,  0.5234047 ],
       [-0.2612776 , -0.14231075,  0.14617191, ..., -0.12022004,
         0.02360877,  0.30352536],
       [-0.33666512,  0.2653478 , -0.01160252, ..., -0.8548789 ,
         0.55941284,  0.36831278]], dtype=float32)

#**df10**

In [ ]:
df10.shape

(2000, 7)

In [ ]:
pair10=df10['Title1'] + df10['Description1']+ [" [SEP] "] + df10['Title2'] + df10['Description2']
tokenized10 = pair10.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair10= df10['Title1'] + [" [SEP] "] + df10['Title2'] 
tokenized10 = pair10.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len10 = 0                 # padding all lists to the same size
for i in tokenized10.values:
    if len(i) > max_len10:
        max_len10 = len(i)
max_len10=400
padded10 = np.array([i + [0]*(max_len10-len(i)) for i in tokenized10.values])

np.array(padded10).shape        # Dimensions of the padded variable        

(1000, 400)

In [ ]:
attention_mask10 = np.where(padded10 != 0, 1, 0)
attention_mask10.shape
input_ids10 = torch.tensor(padded10)  
attention_mask10 = torch.tensor(attention_mask10)
input_segments10= np.array([_get_segments3(token, max_len10)for token in tokenized10.values])
token_type_ids10 = torch.tensor(input_segments10)
input_segments10 = torch.tensor(input_segments10)

In [ ]:
with torch.no_grad():
    last_hidden_states10 = model(input_ids10, attention_mask=attention_mask10, token_type_ids=input_segments10) 
features10 = last_hidden_states10[0][:,0,:].numpy()
features10


array([[-0.7221755 ,  0.08685371, -0.62505007, ..., -0.703207  ,
         0.10335644,  0.30196762],
       [-0.67629796, -0.22116122, -0.64700085, ..., -0.55258566,
         0.0359427 ,  0.73518294],
       [-0.8637359 ,  0.27556342, -0.6522816 , ..., -0.7595745 ,
         0.1782548 ,  0.14752032],
       ...,
       [-0.7972807 , -0.3109028 , -0.22895038, ..., -0.15146983,
        -0.15157846,  0.6087385 ],
       [-0.5505137 , -0.3646421 , -0.6665446 , ..., -0.6581968 ,
        -0.4750822 ,  0.7696816 ],
       [-0.63020384,  0.09093462, -0.03568752, ..., -0.8430675 ,
        -0.10231688,  0.45327637]], dtype=float32)

#**df11**

In [ ]:
pair11=df11['Title1'] + df11['Description1']+ [" [SEP] "] + df11['Title2'] + df11['Description2']
tokenized11 = pair11.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair11= df11['Title1'] + [" [SEP] "] + df11['Title2'] 
tokenized11 = pair11.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len11 = 0                 # padding all lists to the same size
for i in tokenized11.values:
    if len(i) > max_len11:
        max_len11 = len(i)
max_len11=400
padded11 = np.array([i + [0]*(max_len11-len(i)) for i in tokenized11.values])

np.array(padded11).shape        # Dimensions of the padded variable        

(858, 400)

In [ ]:
attention_mask11 = np.where(padded11 != 0, 1, 0)
attention_mask11.shape
input_ids11 = torch.tensor(padded11)  
attention_mask11 = torch.tensor(attention_mask11)
input_segments11= np.array([_get_segments3(token, max_len11)for token in tokenized11.values])
token_type_ids11 = torch.tensor(input_segments11)
input_segments11 = torch.tensor(input_segments11)

In [ ]:
with torch.no_grad():
    last_hidden_states11 = model(input_ids11, attention_mask=attention_mask11, token_type_ids=input_segments11)   
features11 = last_hidden_states11[0][:,0,:].numpy()
features11    

array([[-1.0965941 , -0.32594132, -0.6293237 , ..., -0.7312953 ,
        -0.07185886,  0.47303402],
       [-0.8496082 , -0.01324621, -0.7158931 , ..., -0.54982394,
        -0.11152653,  0.6041019 ],
       [-0.79878354,  0.03131584, -0.7389505 , ..., -0.8986228 ,
        -0.39990905,  0.43480495],
       ...,
       [-0.8424961 , -0.1388742 , -0.43457323, ..., -0.6201381 ,
        -0.42709693,  0.5619997 ],
       [-0.88656753,  0.15510209, -0.39167368, ..., -0.8619249 ,
        -0.04393776,  0.55503464],
       [-0.56027085,  0.13850543, -0.39666793, ..., -0.33967277,
         0.3233898 ,  0.43762138]], dtype=float32)

#**df12**

In [ ]:
pair12=df12['Title1'] + df12['Description1']+ [" [SEP] "] + df12['Title2'] + df12['Description2']
tokenized12 = pair12.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
pair12= df12['Title1'] + [" [SEP] "] + df12['Title2'] 
tokenized12 = pair12.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len12 = 0                 # padding all lists to the same size
for i in tokenized12.values:
    if len(i) > max_len12:
        max_len12 = len(i)
max_len12=400
padded12 = np.array([i + [0]*(max_len12-len(i)) for i in tokenized12.values])

np.array(padded12).shape        # Dimensions of the padded variable        

(1000, 400)

In [ ]:
attention_mask12 = np.where(padded12 != 0, 1, 0)
attention_mask12.shape
input_ids12 = torch.tensor(padded12)  
attention_mask12 = torch.tensor(attention_mask12)
input_segments12= np.array([_get_segments3(token, max_len12)for token in tokenized12.values])
token_type_ids12 = torch.tensor(input_segments12)
input_segments12 = torch.tensor(input_segments12)

In [ ]:
with torch.no_grad():
    last_hidden_states12 = model(input_ids12, attention_mask=attention_mask12, token_type_ids=input_segments12)  
features12 = last_hidden_states12[0][:,0,:].numpy()
features12    

array([[-0.9098713 , -0.04813258, -0.89414257, ..., -1.0398788 ,
         0.15110603,  0.26275992],
       [-1.0552098 ,  0.10414907, -0.41513225, ..., -0.6794574 ,
         0.39839414, -0.02163483],
       [-1.0088667 , -0.07270437, -0.42814118, ..., -1.2012852 ,
         0.02754997,  0.6207006 ],
       ...,
       [-1.0227047 , -0.09186717, -0.3867375 , ..., -0.92605686,
        -0.33967513,  0.80124265],
       [-0.6632688 , -0.11405732, -0.67114943, ..., -0.7918212 ,
        -0.17856218,  0.6456375 ],
       [-0.45858434, -0.12487756, -0.2535239 , ..., -1.0003226 ,
        -0.05667063,  0.8517666 ]], dtype=float32)

#**df13**

In [ ]:
#df13=df2[5500:6000]

In [ ]:
pair13= df13['Title1'] + [" [SEP] "] + df13['Title2'] 
#pair13=df13['Title1'] + df13['Description1']+ [" [SEP] "] + df13['Title2'] + df13['Description2']
tokenized13 = pair13.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len13 = 0                 # padding all lists to the same size
for i in tokenized13.values:
    if len(i) > max_len13:
        max_len13 = len(i)
max_len13=400
padded13 = np.array([i + [0]*(max_len13-len(i)) for i in tokenized13.values])

np.array(padded13).shape        # Dimensions of the padded variable

attention_mask13 = np.where(padded13 != 0, 1, 0)
attention_mask13.shape
input_ids13 = torch.tensor(padded13)  
attention_mask13 = torch.tensor(attention_mask13)
input_segments13= np.array([_get_segments3(token, max_len13)for token in tokenized13.values])
token_type_ids13 = torch.tensor(input_segments13)
input_segments13 = torch.tensor(input_segments13)

In [ ]:
with torch.no_grad():
    last_hidden_states13 = model(input_ids13, attention_mask=attention_mask13, token_type_ids=input_segments13)  
features13 = last_hidden_states13[0][:,0,:].numpy()
features13    

array([[-0.99313295, -0.05476919, -0.80976295, ..., -0.87357974,
         0.00614867,  0.2473064 ],
       [-0.49024   ,  0.20279084, -0.25830904, ..., -0.6609863 ,
         0.12792121,  0.5918789 ],
       [-0.9173766 ,  0.34492496, -1.0704291 , ..., -0.67928576,
         0.07558428,  0.21830314],
       ...,
       [-0.91869694, -0.00967777, -0.792399  , ..., -0.8067743 ,
        -0.2540713 ,  0.84941584],
       [-0.44784528, -0.22839631, -0.20326129, ..., -0.65628934,
        -0.22542752,  0.5295107 ],
       [-0.59516156, -0.24212041, -0.175034  , ..., -0.8554445 ,
         0.10121493,  0.42806044]], dtype=float32)

#**df14**

In [ ]:
#df14=df2[6000:6500]

In [ ]:
pair14= df14['Title1'] + [" [SEP] "] + df14['Title2'] 
#pair14=df14['Title1'] + df14['Description1']+ [" [SEP] "] + df14['Title2']  + df14['Description2']
tokenized14 = pair14.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len14 = 0                 # padding all lists to the same size
for i in tokenized14.values:
    if len(i) > max_len14:
        max_len14 = len(i)
max_len14=400
padded14 = np.array([i + [0]*(max_len14-len(i)) for i in tokenized14.values])

np.array(padded14).shape     

attention_mask14 = np.where(padded14 != 0, 1, 0)
attention_mask14.shape
input_ids14 = torch.tensor(padded14)  
attention_mask14 = torch.tensor(attention_mask14)
input_segments14= np.array([_get_segments3(token, max_len14)for token in tokenized14.values])
token_type_ids14 = torch.tensor(input_segments14)
input_segments14 = torch.tensor(input_segments14)

In [ ]:
with torch.no_grad():
    last_hidden_states14 = model(input_ids14, attention_mask=attention_mask14, token_type_ids=input_segments14)  
features14 = last_hidden_states14[0][:,0,:].numpy()
features14    

array([[-0.9477413 , -0.2618782 , -0.10999456, ..., -0.900821  ,
        -0.2064147 ,  0.7947727 ],
       [-0.48339632,  0.22094476, -0.19013324, ..., -0.79504925,
         0.12616032,  0.39043587],
       [-0.7738631 , -0.12383427, -0.39629352, ..., -0.9080751 ,
         0.32653576,  0.4971729 ],
       ...,
       [-1.1429377 , -0.0550036 , -0.39170918, ..., -1.152537  ,
        -0.05840421,  0.13671932],
       [-0.38378823, -0.0138146 ,  0.05110237, ..., -0.9315654 ,
         0.17561652,  0.45901486],
       [-1.0530888 ,  0.02799437, -0.5486532 , ..., -1.1006713 ,
        -0.20984267,  0.67518973]], dtype=float32)

#**df15**

In [ ]:
#df15=df2[6500:7000]

In [ ]:
pair15= df15['Title1'] + [" [SEP] "] + df15['Title2'] 
#pair15=df15['Title1'] + df15['Description1']+ [" [SEP] "] + df15['Title2']  + df15['Description2']
tokenized15 = pair15.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len15 = 0                 # padding all lists to the same size
for i in tokenized15.values:
    if len(i) > max_len15:
        max_len15 = len(i)
max_len15=400
padded15 = np.array([i + [0]*(max_len15-len(i)) for i in tokenized15.values])

np.array(padded15).shape      

attention_mask15 = np.where(padded15 != 0, 1, 0)
attention_mask15.shape
input_ids15 = torch.tensor(padded15)  
attention_mask15 = torch.tensor(attention_mask15)
input_segments15= np.array([_get_segments3(token, max_len15)for token in tokenized15.values])
token_type_ids15 = torch.tensor(input_segments15)
input_segments15 = torch.tensor(input_segments15)

In [ ]:
with torch.no_grad():
    last_hidden_states15 = model(input_ids15, attention_mask=attention_mask15, token_type_ids=input_segments15)  
features15 = last_hidden_states15[0][:,0,:].numpy()
features15    

array([[-0.634696  ,  0.4397773 , -0.38158074, ..., -0.7503303 ,
        -0.07677691,  0.44228888],
       [-0.6914888 ,  0.06672204, -0.36002332, ..., -0.795171  ,
         0.16754016,  0.6432465 ],
       [-1.039531  , -0.0238276 , -0.30765155, ..., -0.8447843 ,
        -0.03071452,  0.10016486],
       ...,
       [-0.3976697 ,  0.23359518, -0.5089712 , ..., -0.5545944 ,
         0.32298282,  0.9118142 ],
       [-0.41895574,  0.27283552, -0.41096437, ..., -0.70541275,
         0.13409577,  0.8102837 ],
       [-0.58075464, -0.52542925, -0.05581212, ..., -0.8229134 ,
        -0.10039041,  0.7953049 ]], dtype=float32)

#**df16**

In [ ]:
pair16= df16['Title1'] + [" [SEP] "] + df16['Title2'] 
#df16=df2[7000:7500]
#pair16=df16['Title1'] + df16['Description1']+ [" [SEP] "] + df16['Title2']  + df16['Description2']
tokenized16 = pair16.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len16 = 0                 # padding all lists to the same size
for i in tokenized16.values:
    if len(i) > max_len16:
        max_len16 = len(i)
max_len16=400
padded16 = np.array([i + [0]*(max_len16-len(i)) for i in tokenized16.values])

np.array(padded16).shape   

attention_mask16 = np.where(padded16 != 0, 1, 0)
attention_mask16.shape
input_ids16 = torch.tensor(padded16)  
attention_mask16 = torch.tensor(attention_mask16)
input_segments16= np.array([_get_segments3(token, max_len16)for token in tokenized16.values])
token_type_ids16 = torch.tensor(input_segments16)
input_segments16 = torch.tensor(input_segments16)

In [ ]:
with torch.no_grad():
    last_hidden_states16 = model(input_ids16, attention_mask=attention_mask16, token_type_ids=input_segments16) 
features16 = last_hidden_states16[0][:,0,:].numpy()
features16    

array([[-0.5629982 , -0.22359931,  0.01177346, ..., -0.78597516,
        -0.11223599,  0.4817627 ],
       [-0.93734443, -0.03238021, -0.59226674, ..., -0.98203564,
         0.07429168,  0.43507808],
       [-0.9727847 , -0.04769222, -0.65850997, ..., -0.9747521 ,
         0.22724082,  0.52176285],
       ...,
       [-0.53101826, -0.4070981 , -0.3324958 , ..., -0.86640275,
         0.04076444,  0.49889955],
       [-0.44350076, -0.06732277,  0.10912675, ..., -0.7839072 ,
         0.01696949,  0.5203878 ],
       [-0.5935867 , -0.3483018 , -0.10235156, ..., -0.42957467,
        -0.25433266,  0.6587252 ]], dtype=float32)

#**df17**

In [ ]:
#df17=df2[7500:8000]
pair17= df17['Title1'] + [" [SEP] "] + df17['Title2'] 
#pair17=df17['Title1'] + df17['Description1']+ [" [SEP] "] + df17['Title2']  + df17['Description2']
tokenized17 = pair17.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len17 = 0                 # padding all lists to the same size
for i in tokenized17.values:
    if len(i) > max_len17:
        max_len17 = len(i)
max_len17=400
padded17 = np.array([i + [0]*(max_len17-len(i)) for i in tokenized17.values])

np.array(padded17).shape       

attention_mask17 = np.where(padded17 != 0, 1, 0)
attention_mask17.shape
input_ids17 = torch.tensor(padded17)  
attention_mask17 = torch.tensor(attention_mask17)
input_segments17= np.array([_get_segments3(token, max_len17)for token in tokenized17.values])
token_type_ids17 = torch.tensor(input_segments17)
input_segments17 = torch.tensor(input_segments17)

In [ ]:
with torch.no_grad():
    last_hidden_states17 = model(input_ids17, attention_mask=attention_mask17, token_type_ids=input_segments17)
features17 = last_hidden_states17[0][:,0,:].numpy()
features17    

array([[-0.9424098 , -0.23053767, -0.7857819 , ..., -0.5907442 ,
        -0.09202828,  0.5897986 ],
       [-0.9578878 ,  0.2815496 , -0.93701416, ..., -0.9624418 ,
         0.36296406,  0.51745415],
       [-0.86430097, -0.32785556, -0.78144455, ..., -0.8755779 ,
         0.08258668,  0.2789431 ],
       ...,
       [-0.2654646 , -0.06870487, -0.17975861, ..., -0.71111876,
         0.01659222,  0.65306526],
       [-0.58717865,  0.20979802, -0.29732856, ..., -0.82854974,
        -0.3322833 ,  0.6185815 ],
       [-0.8882877 ,  0.00417061, -0.3285587 , ..., -0.9314255 ,
        -0.19815792,  0.5861041 ]], dtype=float32)

#**df18**

In [ ]:
pair18= df18['Title1'] + [" [SEP] "] + df18['Title2'] 

#pair18=df18['Title1'] + df18['Description1']+ [" [SEP] "] + df18['Title2']  + df18['Description2']
tokenized18 = pair18.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len18 = 0                 # padding all lists to the same size
for i in tokenized18.values:
    if len(i) > max_len18:
        max_len18 = len(i)
max_len18=400
padded18 = np.array([i + [0]*(max_len18-len(i)) for i in tokenized18.values])

np.array(padded18).shape     

attention_mask18 = np.where(padded18 != 0, 1, 0)
attention_mask18.shape
input_ids18 = torch.tensor(padded18)  
attention_mask18 = torch.tensor(attention_mask18)
input_segments18= np.array([_get_segments3(token, max_len18)for token in tokenized18.values])
token_type_ids18 = torch.tensor(input_segments18)
input_segments18 = torch.tensor(input_segments18)

In [ ]:
with torch.no_grad():
    last_hidden_states18 = model(input_ids18, attention_mask=attention_mask18, token_type_ids=input_segments18)
features18 = last_hidden_states18[0][:,0,:].numpy()
features18

array([[-0.70983565, -0.02601749, -0.5128192 , ..., -0.8397139 ,
         0.08668627,  0.40085024],
       [-1.0198691 , -0.30174673, -0.47517964, ..., -0.9683191 ,
        -0.2931103 ,  0.33569872],
       [-1.1243756 , -0.20700757, -0.76653665, ..., -0.65540415,
        -0.19021983,  0.86698174],
       ...,
       [-0.837647  , -0.2766569 , -0.638373  , ..., -0.5233455 ,
        -0.6114669 ,  0.57889605],
       [-0.5482467 , -0.35647   , -0.29398933, ..., -0.9184335 ,
        -0.22654827,  0.6063546 ],
       [-0.5216297 , -0.15811397,  0.15959908, ..., -0.73848826,
         0.07056168,  0.7684073 ]], dtype=float32)

#**df19**

In [ ]:
pair19= df19['Title1'] + [" [SEP] "] + df19['Title2'] 

#pair19=df19['Title1'] + df19['Description1']+ [" [SEP] "] + df19['Title2']  + df19['Description2']
tokenized19 = pair19.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len19 = 0                 # padding all lists to the same size
for i in tokenized19.values:
    if len(i) > max_len19:
        max_len19 = len(i)
max_len19=400
padded19 = np.array([i + [0]*(max_len19-len(i)) for i in tokenized19.values])

np.array(padded19).shape    

attention_mask19 = np.where(padded19 != 0, 1, 0)
attention_mask19.shape
input_ids19 = torch.tensor(padded19)  
attention_mask19 = torch.tensor(attention_mask19)
input_segments19= np.array([_get_segments3(token, max_len19)for token in tokenized19.values])
token_type_ids19 = torch.tensor(input_segments19)
input_segments19 = torch.tensor(input_segments19)

In [ ]:
with torch.no_grad():
    last_hidden_states19 = model(input_ids19, attention_mask=attention_mask19, token_type_ids=input_segments19)
features19 = last_hidden_states19[0][:,0,:].numpy()
features19

array([[-0.7437526 ,  0.00850332, -0.23081304, ..., -0.7144467 ,
        -0.13111687,  0.50495845],
       [-1.1171824 , -0.07899722, -0.2040811 , ..., -0.92751664,
         0.37972355,  0.41935024],
       [-0.9601478 ,  0.06865299, -0.72377324, ..., -0.8351683 ,
         0.43380022,  0.6006958 ],
       ...,
       [-0.62437034, -0.09127276, -0.6086664 , ..., -0.80698174,
         0.05990908,  0.58689815],
       [-0.7748073 , -0.0032856 , -0.18465956, ..., -0.80536586,
         0.02100786,  0.42420498],
       [-0.24878651,  0.13388427, -0.08130744, ..., -0.80852956,
         0.3894577 ,  0.47119716]], dtype=float32)

#**df20**

In [ ]:
pair20= df20['Title1'] + [" [SEP] "] + df20['Title2'] 

#pair20=df20['Title1'] + df20['Description1']+ [" [SEP] "] + df20['Title2']  + df20['Description2']
tokenized20 = pair20.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len20 = 0                 # padding all lists to the same size
for i in tokenized20.values:
    if len(i) > max_len20:
        max_len20 = len(i)
max_len20=400
padded20 = np.array([i + [0]*(max_len20-len(i)) for i in tokenized20.values])

np.array(padded20).shape        

attention_mask20 = np.where(padded20 != 0, 1, 0)
attention_mask20.shape
input_ids20 = torch.tensor(padded20)  
attention_mask20 = torch.tensor(attention_mask20)
input_segments20= np.array([_get_segments3(token, max_len20)for token in tokenized20.values])
token_type_ids20 = torch.tensor(input_segments20)
input_segments20 = torch.tensor(input_segments20)

In [ ]:
with torch.no_grad():
    last_hidden_states20 = model(input_ids20, attention_mask=attention_mask20, token_type_ids=input_segments20)
features20 = last_hidden_states20[0][:,0,:].numpy()
features20

array([[-0.93893653, -0.3074492 , -0.43752205, ..., -1.0350488 ,
         0.19421567,  0.22676192],
       [-1.2543483 , -0.246138  , -0.8669419 , ..., -0.94334376,
         0.09963596,  0.27141947],
       [-0.98340863,  0.34436497, -0.6175991 , ..., -1.0077778 ,
         0.2750777 ,  0.566506  ],
       ...,
       [-0.8394962 , -0.15229735, -0.4249453 , ..., -0.7942943 ,
        -0.04718928,  0.42587578],
       [-0.7293618 , -0.19182543, -0.3004849 , ..., -0.97465575,
        -0.1126556 ,  0.6648691 ],
       [-0.7821136 , -0.05275391, -0.2450732 , ..., -0.81457216,
        -0.18013947,  0.65601414]], dtype=float32)

#**df21**

In [ ]:
pair21= df21['Title1'] + [" [SEP] "] + df21['Title2'] 

#pair21=df21['Title1'] + df21['Description1']+ [" [SEP] "] + df21['Title2']  + df21['Description2']
tokenized21 = pair21.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len21 = 0                 # padding all lists to the same size
for i in tokenized21.values:
    if len(i) > max_len21:
        max_len21 = len(i)
max_len21=400
padded21 = np.array([i + [0]*(max_len21-len(i)) for i in tokenized21.values])

np.array(padded21).shape   

attention_mask21 = np.where(padded21 != 0, 1, 0)
attention_mask21.shape
input_ids21 = torch.tensor(padded21)  
attention_mask21 = torch.tensor(attention_mask21)
input_segments21= np.array([_get_segments3(token, max_len21)for token in tokenized21.values])
token_type_ids21 = torch.tensor(input_segments21)
input_segments21 = torch.tensor(input_segments21)

In [ ]:
with torch.no_grad():
    last_hidden_states21 = model(input_ids21, attention_mask=attention_mask21, token_type_ids=input_segments21)
features21 = last_hidden_states21[0][:,0,:].numpy()
features21

array([[-0.92391443, -0.43056396,  0.01055484, ..., -0.7028444 ,
         0.52767617,  0.3057289 ],
       [-0.71694463,  0.03697701, -0.15843478, ..., -0.7756225 ,
         0.24404155,  0.41296685],
       [-0.7292778 , -0.45057297, -0.5103143 , ..., -0.86111426,
        -0.04123855,  0.6854649 ],
       ...,
       [-0.8041957 , -0.32317016, -0.4104845 , ..., -0.86852807,
         0.17493635,  0.65697163],
       [-0.45336986,  0.3260496 , -0.00856491, ..., -0.82632697,
         0.22707944,  0.72186923],
       [-0.7686214 , -0.47788548, -0.6213597 , ..., -0.6941872 ,
        -0.3461387 ,  0.6983035 ]], dtype=float32)

#**df22**

In [ ]:
pair22= df22['Title1'] + [" [SEP] "] + df22['Title2'] 

#pair22=df22['Title1'] + df22['Description1']+ [" [SEP] "] + df22['Title2']  + df22['Description2']
tokenized22 = pair22.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len22 = 0                 # padding all lists to the same size
for i in tokenized22.values:
    if len(i) > max_len22:
        max_len22 = len(i)
max_len22=400
padded22 = np.array([i + [0]*(max_len22-len(i)) for i in tokenized22.values])
np.array(padded22).shape   

attention_mask22 = np.where(padded22 != 0, 1, 0)
attention_mask22.shape
input_ids22 = torch.tensor(padded22)  
attention_mask22 = torch.tensor(attention_mask22)
input_segments22= np.array([_get_segments3(token, max_len22)for token in tokenized22.values])
token_type_ids22 = torch.tensor(input_segments22)
input_segments22 = torch.tensor(input_segments22)

In [ ]:
with torch.no_grad():
    last_hidden_states22 = model(input_ids22, attention_mask=attention_mask22, token_type_ids=input_segments22)
features22 = last_hidden_states22[0][:,0,:].numpy()
features22

array([[-1.1227669 , -0.53095734, -0.6710377 , ..., -1.0260364 ,
        -0.17136404,  0.5021251 ],
       [-0.37664807, -0.08216803, -0.18968922, ..., -0.485305  ,
        -0.21002148,  0.5545706 ],
       [-0.9587333 , -0.01371935, -0.60748935, ..., -0.702922  ,
         0.03198466,  0.65272224],
       ...,
       [-0.6949298 , -0.5690475 , -0.10136634, ..., -0.385616  ,
        -0.33018896,  0.42975008],
       [-0.5209979 ,  0.31820196, -0.2732457 , ..., -0.9961297 ,
         0.47437274,  0.6684551 ],
       [-0.43084964,  0.04925112, -0.32863766, ..., -0.6574368 ,
        -0.01415461,  0.6376334 ]], dtype=float32)

#**df23**

In [ ]:
pair23= df23['Title1'] + [" [SEP] "] + df23['Title2'] 

#pair23=df23['Title1'] + df23['Description1']+ [" [SEP] "] + df23['Title2']  + df23['Description2']
tokenized23 = pair23.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len23 = 0                 # padding all lists to the same size
for i in tokenized23.values:
    if len(i) > max_len23:
        max_len23 = len(i)
max_len23=400
padded23 = np.array([i + [0]*(max_len23-len(i)) for i in tokenized23.values])

np.array(padded23).shape   

attention_mask23 = np.where(padded23 != 0, 1, 0)
attention_mask23.shape
input_ids23 = torch.tensor(padded23)  
attention_mask23 = torch.tensor(attention_mask23)
input_segments23= np.array([_get_segments3(token, max_len23)for token in tokenized23.values])
token_type_ids23 = torch.tensor(input_segments23)
input_segments23 = torch.tensor(input_segments23)

In [ ]:
with torch.no_grad():
    last_hidden_states23 = model(input_ids23, attention_mask=attention_mask23, token_type_ids=input_segments23)
features23 = last_hidden_states23[0][:,0,:].numpy()
features23

array([[-1.2091132 , -0.21107084, -0.8005135 , ..., -1.136774  ,
         0.09916731,  0.59666014],
       [-0.8888612 , -0.19540344, -0.22997002, ..., -1.0528963 ,
         0.02220004,  0.20271657],
       [-0.5883753 ,  0.01558063, -0.51211417, ..., -0.7975305 ,
        -0.03869688,  0.42295304],
       ...,
       [-0.65238667,  0.01385008, -0.6317031 , ..., -1.0780437 ,
         0.06382644,  0.44884706],
       [-0.667511  , -0.3038854 , -0.22280337, ..., -0.59497577,
        -0.23609984,  0.6422316 ],
       [-0.32928675, -0.25583842, -0.3238151 , ..., -0.89867854,
        -0.09509396,  0.7873074 ]], dtype=float32)

#**df24**

In [ ]:
pair24= df24['Title1'] + [" [SEP] "] + df24['Title2'] 

#pair24=df24['Title1'] + df24['Description1']+ [" [SEP] "] + df24['Title2']  + df24['Description2']
tokenized24 = pair24.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len24 = 0                 # padding all lists to the same size
for i in tokenized24.values:
    if len(i) > max_len24:
        max_len24 = len(i)
max_len24=400
padded24 = np.array([i + [0]*(max_len24-len(i)) for i in tokenized24.values])
np.array(padded24).shape   

attention_mask24 = np.where(padded24 != 0, 1, 0)
attention_mask24.shape
input_ids24 = torch.tensor(padded24)  
attention_mask24 = torch.tensor(attention_mask24)
input_segments24= np.array([_get_segments3(token, max_len24)for token in tokenized24.values])
token_type_ids24 = torch.tensor(input_segments24)
input_segments24 = torch.tensor(input_segments24)

In [ ]:
with torch.no_grad():
    last_hidden_states24 = model(input_ids24, attention_mask=attention_mask24, token_type_ids=input_segments24)
features24 = last_hidden_states24[0][:,0,:].numpy()
features24

array([[-0.86608416,  0.17215776, -0.46730685, ..., -0.9206102 ,
         0.38783476,  0.5104863 ],
       [-1.122852  , -0.00970626, -0.57225615, ..., -0.9707822 ,
         0.08788388,  0.4584177 ],
       [-0.99631935, -0.10670024, -0.35201016, ..., -1.0520109 ,
         0.11884421,  0.527576  ],
       ...,
       [-0.38410023,  0.08111908, -0.20096868, ..., -0.7469904 ,
         0.02661499,  0.8539093 ],
       [-0.662188  , -0.11769716, -0.32121372, ..., -0.74243325,
        -0.07443971,  0.51434547],
       [-0.53217703,  0.05877384, -0.46078193, ..., -0.79777205,
        -0.3520375 ,  0.51242507]], dtype=float32)

#**df25**

In [ ]:
pair25= df25['Title1'] + [" [SEP] "] + df25['Title2'] 

#pair25=df25['Title1'] + df25['Description1']+ [" [SEP] "] + df25['Title2']  + df25['Description2']
tokenized25 = pair25.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len25 = 0                 # padding all lists to the same size
for i in tokenized25.values:
    if len(i) > max_len25:
        max_len25 = len(i)
max_len25=400
padded25 = np.array([i + [0]*(max_len25-len(i)) for i in tokenized25.values])

np.array(padded25).shape   

attention_mask25 = np.where(padded25 != 0, 1, 0)
attention_mask25.shape
input_ids25 = torch.tensor(padded25)  
attention_mask25 = torch.tensor(attention_mask25)
input_segments25= np.array([_get_segments3(token, max_len25)for token in tokenized25.values])
token_type_ids25 = torch.tensor(input_segments25)
input_segments25 = torch.tensor(input_segments25)

In [ ]:
with torch.no_grad():
    last_hidden_states25 = model(input_ids25, attention_mask=attention_mask25, token_type_ids=input_segments25)
features25 = last_hidden_states25[0][:,0,:].numpy()
features25

array([[-0.48258132,  0.03612053, -0.1766388 , ..., -0.75295615,
        -0.13577694,  0.62956375],
       [-0.8370008 ,  0.16011171, -0.04330045, ..., -0.95591456,
         0.10296807,  0.28306046],
       [-1.1009042 ,  0.03289679, -0.5432754 , ..., -0.7914779 ,
         0.25787523,  0.42429048],
       ...,
       [-0.8114431 , -0.08565717, -0.5200243 , ..., -0.525949  ,
        -0.02620442,  0.51802087],
       [-0.6483376 , -0.37717983, -0.54648626, ..., -0.7991549 ,
        -0.07482868,  0.62967515],
       [-0.5346423 ,  0.10205352, -0.42738006, ..., -0.49585527,
        -0.168702  ,  0.85295314]], dtype=float32)

#**df26**

In [ ]:
pair26= df26['Title1'] + [" [SEP] "] + df26['Title2'] 

#pair26=df26['Title1'] + df26['Description1']+ [" [SEP] "] + df26['Title2']  + df26['Description2']
tokenized26 = pair26.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len26 = 0                 # padding all lists to the same size
for i in tokenized26.values:
    if len(i) > max_len26:
        max_len26 = len(i)
max_len26=400
padded26 = np.array([i + [0]*(max_len26-len(i)) for i in tokenized26.values])

np.array(padded26).shape   

attention_mask26 = np.where(padded26 != 0, 1, 0)
attention_mask26.shape
input_ids26 = torch.tensor(padded26)  
attention_mask26 = torch.tensor(attention_mask26)
input_segments26= np.array([_get_segments3(token, max_len26)for token in tokenized26.values])
token_type_ids26 = torch.tensor(input_segments26)
input_segments26 = torch.tensor(input_segments26)

In [ ]:
with torch.no_grad():
    last_hidden_states26 = model(input_ids26, attention_mask=attention_mask26, token_type_ids=input_segments26)
features26 = last_hidden_states26[0][:,0,:].numpy()
features26

array([[-0.7684134 ,  0.33454967, -0.69491535, ..., -0.9386668 ,
        -0.14966685,  0.7849923 ],
       [-0.78016907,  0.19756602, -0.6089295 , ..., -0.85715103,
        -0.05772907,  0.48598388],
       [-0.8612882 ,  0.3293334 , -0.631693  , ..., -0.6989362 ,
        -0.11895953,  0.6769287 ],
       ...,
       [-0.74312747, -0.2882465 , -0.38506988, ..., -0.72542965,
        -0.03297152,  0.4223961 ],
       [-0.69973016, -0.1439958 , -0.33223903, ..., -1.0342978 ,
        -0.09001105,  0.4708787 ],
       [-1.2020993 , -0.21611896, -0.21625882, ..., -0.7088391 ,
         0.00993042,  0.18998945]], dtype=float32)

#**df28**

In [ ]:
pair27= df27['Title1'] + [" [SEP] "] + df27['Title2'] 

#pair27=df27['Title1'] + df27['Description1']+ [" [SEP] "] + df27['Title2']  + df27['Description2']
tokenized27 = pair27.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len27 = 0                 # padding all lists to the same size
for i in tokenized27.values:
    if len(i) > max_len27:
        max_len27 = len(i)
max_len27=400
padded27 = np.array([i + [0]*(max_len27-len(i)) for i in tokenized27.values])

np.array(padded27).shape   

attention_mask27 = np.where(padded27 != 0, 1, 0)
attention_mask27.shape
input_ids27 = torch.tensor(padded27)  
attention_mask27 = torch.tensor(attention_mask27)
input_segments27= np.array([_get_segments3(token, max_len27)for token in tokenized27.values])
token_type_ids27 = torch.tensor(input_segments27)
input_segments27 = torch.tensor(input_segments27)

In [ ]:
with torch.no_grad():
    last_hidden_states27 = model(input_ids27, attention_mask=attention_mask27, token_type_ids=input_segments27)
features27 = last_hidden_states27[0][:,0,:].numpy()
features27

array([[-1.1053605 , -0.20529044, -0.43549475, ..., -1.0083389 ,
        -0.12894097,  0.47416714],
       [-0.90495896,  0.3721126 , -0.6449153 , ..., -0.8027362 ,
        -0.11034597,  0.38074028],
       [-0.8387609 ,  0.02298694, -0.1684745 , ..., -0.71781474,
         0.08543791,  0.3238307 ],
       ...,
       [-0.7039172 , -0.26324615, -0.6720394 , ..., -0.54843265,
        -0.03257831,  0.2716309 ],
       [-0.95956486, -0.30222815, -0.2621101 , ..., -0.714451  ,
         0.06528066,  0.49777877],
       [-0.5107403 ,  0.10252057,  0.18395726, ..., -0.77943087,
         0.3432232 ,  0.4051083 ]], dtype=float32)

#**df29**

In [ ]:
pair28= df28['Title1'] + [" [SEP] "] + df28['Title2'] 

#pair28=df28['Title1'] + df28['Description1']+ [" [SEP] "] + df28['Title2']  + df28['Description2']
tokenized28 = pair28.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len28 = 0                 # padding all lists to the same size
for i in tokenized28.values:
    if len(i) > max_len28:
        max_len28 = len(i)
max_len28=400
padded28 = np.array([i + [0]*(max_len28-len(i)) for i in tokenized28.values])

np.array(padded28).shape   

attention_mask28 = np.where(padded28 != 0, 1, 0)
attention_mask28.shape
input_ids28 = torch.tensor(padded28)  
attention_mask28 = torch.tensor(attention_mask21)
input_segments28= np.array([_get_segments3(token, max_len21)for token in tokenized28.values])
token_type_ids28 = torch.tensor(input_segments28)
input_segments28 = torch.tensor(input_segments28)

In [ ]:
with torch.no_grad():
    last_hidden_states28 = model(input_ids28, attention_mask=attention_mask28, token_type_ids=input_segments28)
features28 = last_hidden_states28[0][:,0,:].numpy()
features28

array([[-0.9537438 , -0.2981415 , -0.31189132, ..., -0.6201275 ,
        -0.00979078,  0.35831913],
       [-0.684181  , -0.34284735, -0.11722674, ..., -0.6870205 ,
         0.55050284,  0.3322232 ],
       [-1.1432269 ,  0.19532573, -0.31382412, ..., -0.46242324,
         0.4534321 ,  0.07063413],
       ...,
       [-0.57222116, -0.11134218, -0.473794  , ..., -0.7300555 ,
        -0.4053459 ,  0.7415051 ],
       [-0.8070642 ,  0.13288054, -0.07404994, ..., -0.79850173,
         0.08625394,  0.5893098 ],
       [-0.61083174, -0.15951282, -0.15810257, ..., -0.9429177 ,
        -0.03245712,  0.5915904 ]], dtype=float32)

#**df30**

In [ ]:
pair29= df29['Title1'] + [" [SEP] "] + df29['Title2'] 

#pair29=df29['Title1'] + df29['Description1']+ [" [SEP] "] + df29['Title2']  + df29['Description2']
tokenized29 = pair29.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len29 = 0                 # padding all lists to the same size
for i in tokenized29.values:
    if len(i) > max_len29:
        max_len29 = len(i)
max_len29=400
padded29 = np.array([i + [0]*(max_len29-len(i)) for i in tokenized29.values])

np.array(padded29).shape   

attention_mask29 = np.where(padded29 != 0, 1, 0)
attention_mask29.shape
input_ids29 = torch.tensor(padded29)  
attention_mask29 = torch.tensor(attention_mask29)
input_segments29= np.array([_get_segments3(token, max_len29)for token in tokenized29.values])
token_type_ids29 = torch.tensor(input_segments29)
input_segments29 = torch.tensor(input_segments29)

In [ ]:
with torch.no_grad():
    last_hidden_states29 = model(input_ids29, attention_mask=attention_mask29, token_type_ids=input_segments29)
features29 = last_hidden_states29[0][:,0,:].numpy()
features29

array([[-0.6120206 , -0.19241104, -0.05288897, ..., -0.5201119 ,
        -0.3328282 ,  0.92504776],
       [-0.8783361 , -0.10919984, -0.56912553, ..., -0.93113333,
         0.19714183,  0.3017155 ],
       [-1.0778462 ,  0.03433035, -0.61264795, ..., -0.7075932 ,
         0.35042512,  0.7710731 ],
       ...,
       [-0.560468  ,  0.05455036,  0.001631  , ..., -0.60976255,
        -0.25033414,  0.74459   ],
       [-0.47304094,  0.11335693, -0.3823923 , ..., -0.7166425 ,
         0.18844649,  0.7859631 ],
       [-0.9700722 , -0.35139102, -0.159117  , ..., -1.1125509 ,
        -0.06578925,  0.5917558 ]], dtype=float32)

#**df31**

In [ ]:
pair30= df30['Title1'] + [" [SEP] "] + df30['Title2'] 

#pair30=df30['Title1'] + df30['Description1']+ [" [SEP] "] + df30['Title2']  + df30['Description2']
tokenized30 = pair30.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len30 = 0                 # padding all lists to the same size
for i in tokenized30.values:
    if len(i) > max_len30:
        max_len30 = len(i)
max_len30=400
padded30 = np.array([i + [0]*(max_len30-len(i)) for i in tokenized30.values])

np.array(padded30).shape   

attention_mask30 = np.where(padded30 != 0, 1, 0)
attention_mask30.shape
input_ids30 = torch.tensor(padded30)  
attention_mask30 = torch.tensor(attention_mask30)
input_segments30= np.array([_get_segments3(token, max_len30)for token in tokenized30.values])
token_type_ids30 = torch.tensor(input_segments30)
input_segments30 = torch.tensor(input_segments30)

In [ ]:
with torch.no_grad():
    last_hidden_states30 = model(input_ids30, attention_mask=attention_mask30, token_type_ids=input_segments30)
features30 = last_hidden_states30[0][:,0,:].numpy()
features30

array([[-1.103237  , -0.2617415 , -0.66470134, ..., -0.97716004,
        -0.35261288,  0.30122417],
       [-0.7860904 , -0.47706658, -0.27943733, ..., -0.9510553 ,
        -0.17531939,  0.40624955],
       [-0.8340726 ,  0.01629283, -0.38274142, ..., -0.9274527 ,
         0.20363349,  0.48679113],
       ...,
       [-0.9185326 ,  0.05259138, -0.22831547, ..., -1.1354072 ,
         0.05535968,  0.70099163],
       [-0.7624623 ,  0.07095241, -0.21306396, ..., -1.137578  ,
         0.47105548,  0.63216376],
       [-0.44060254, -0.07348562, -0.1581822 , ..., -0.8722063 ,
        -0.06107512,  0.4172463 ]], dtype=float32)

#**df32**

In [ ]:
pair31= df31['Title1'] + [" [SEP] "] + df31['Title2'] 

#pair31=df31['Title1'] + df31['Description1']+ [" [SEP] "] + df31['Title2']  + df31['Description2']
tokenized31 = pair31.apply((lambda x: tokenizer.encode(x, add_special_tokens=True,truncation=True, max_length=400)))

In [ ]:
max_len31 = 0                 # padding all lists to the same size
for i in tokenized31.values:
    if len(i) > max_len31:
        max_len31 = len(i)
max_len31=400
padded31 = np.array([i + [0]*(max_len31-len(i)) for i in tokenized31.values])

np.array(padded31).shape   

attention_mask31 = np.where(padded31 != 0, 1, 0)
attention_mask31.shape
input_ids31 = torch.tensor(padded31)  
attention_mask31 = torch.tensor(attention_mask31)
input_segments31= np.array([_get_segments3(token, max_len31)for token in tokenized31.values])
token_type_ids31 = torch.tensor(input_segments31)
input_segments31 = torch.tensor(input_segments31)

In [ ]:
with torch.no_grad():
    last_hidden_states31 = model(input_ids31, attention_mask=attention_mask31, token_type_ids=input_segments31)
features31 = last_hidden_states31[0][:,0,:].numpy()
features31

#**Classification**

In [ ]:
features=np.concatenate([features3,features4,features5,features6,features7,features8,features9,features10,features11,features12,features13,features14,features15,features16,features17,features18,features19,features20,features21,features22,features23,features24,features25,features26,features27,features29,features30,features31])

In [ ]:
features=np.concatenate([features3])

In [ ]:
features.shape

(8858, 768)

In [ ]:
Total = pd.concat([df3], ignore_index=True)

In [ ]:
Total

Issue_id  ...  Label
0          25  ...      1
1          40  ...      1
2          48  ...      1
3          61  ...      1
4          94  ...      1
..        ...  ...    ...
995      1981  ...      0
996      1982  ...      0
997      1984  ...      0
998      1985  ...      0
999      1986  ...      0

[1000 rows x 7 columns]

In [ ]:
labels=df3['Label']

In [ ]:
labels =Total['Label']
labels

0      1
1      1
2      1
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Label, Length: 1000, dtype: int64

In [ ]:
train_features = features[0:10000]
train_labels = labels[0:10000]
test_features = features[10000:]
test_labels = labels[10000:]

In [ ]:
train_labels

NameError: ignored

In [ ]:
X_train = train.head(800)
X_test = train.tail(200)
y_train = Y.head(800)
y_test = Y.tail(200)

hold out 

In [ ]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels,test_size=0.2,random_state=42)

#**LogisticRegression Optimized**

---



In [ ]:
#n_splits=2
#cross_val_score=5
parameters = {'C': np.linspace(0.0001, 100, 20)}
grid_search = GridSearchCV(LogisticRegression(), parameters, cv=5)
grid_search.fit(train_features, train_labels)
print('best parameters: ', grid_search.best_params_)
print('best scrores: ', grid_search.best_score_)

best parameters:  {'C': 5.263252631578947}
best scrores:  0.8755405405405405


In [ ]:
lr_clf = LogisticRegression(C=5.26)
lr_clf.fit(train_features, train_labels)


LogisticRegression(C=5.26, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr_clf.score(test_features, test_labels)

0.8778378378378379

In [ ]:
y_predLr = lr_clf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_predLr))
print(confusion_matrix(test_labels, y_predLr))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88      1829
           1       0.92      0.83      0.87      1871

    accuracy                           0.88      3700
   macro avg       0.88      0.88      0.88      3700
weighted avg       0.88      0.88      0.88      3700

[[1690  139]
 [ 313 1558]]


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, y_predLr))

0.8816216216216216


In [ ]:

TP = 890
FN = 90
# FT (14) and TN (12) are not needed in the formuala!
recall = TP / (TP + FN)
print(f"recall: {recall:4.2f}")

recall: 0.91


In [ ]:
TP = 890
FP = 62
# FN (0) and TN (12) are not needed in the formuala!
precision = TP / (TP + FP)
print(f"precision: {precision:4.2f}")

precision: 0.93


In [ ]:
scores = cross_val_score(lr_clf, features, labels,cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.880 (std: 0.020)



#**Decision tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf = DecisionTreeClassifier(max_depth = 500, random_state = 0,criterion='gainracue')

In [ ]:
clf = DecisionTreeClassifier(max_depth = 500, random_state = 0)

In [ ]:
clf.fit(train_features, train_labels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=500, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
y_preddt = clf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_preddt))
print(confusion_matrix(test_labels, y_preddt))

              precision    recall  f1-score   support

           0       0.81      0.84      0.82      1829
           1       0.84      0.81      0.82      1871

    accuracy                           0.82      3700
   macro avg       0.82      0.82      0.82      3700
weighted avg       0.82      0.82      0.82      3700

[[1530  299]
 [ 353 1518]]


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, y_preddt))

0.8237837837837838


In [ ]:
# Predict for 1 observation
clf.predict(test_features)
# Predict for multiple observations
#clf.predict(test_features[0:200])

array([0, 1, 0, ..., 0, 1, 0])

In [ ]:
# The score method returns the accuracy of the model
score = clf.score(test_features, test_labels)
print(score)

0.5765


In [ ]:
scores = cross_val_score(clf, features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.815 (std: 0.015)



#**SVM**

In [ ]:
from sklearn.svm import SVC

In [ ]:

svclassifier = SVC(kernel='linear')
svclassifier.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(test_features)

Kernel : Sigmoid: 0.88 / Linear: 0.92/ rbf:0.9 / poly : 0.9

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels,y_pred))
print(classification_report(test_labels,y_pred))

[[1748  170]
 [ 176 1678]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91      1918
           1       0.91      0.91      0.91      1854

    accuracy                           0.91      3772
   macro avg       0.91      0.91      0.91      3772
weighted avg       0.91      0.91      0.91      3772



In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, y_pred))

0.908271474019088


In [ ]:
param_grid = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=15.0min
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 15.0min remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.8min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.9min
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=12.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.7min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=21.6min
[CV] C=1, gamma=1, kernel=rbf ........................................


In [ ]:
grid.best_params_

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

#Cross_Val

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn import svm

In [ ]:
clf = svm.SVC(kernel='linear')

In [ ]:
scores = cross_val_score(grid, test_labels, y_pred, cv=5)

In [ ]:
scores = cross_val_score(svclassifier,features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.890 (std: 0.012)



#**MLP Best params**

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=500)
from sklearn.datasets import make_classification

parameter_space = {
    'hidden_layer_sizes': [(50,100,50), (50,100,50), (100,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(train_features, train_labels)

GridSearchCV(cv=3, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=500, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state...
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'activation': ['ta

In [ ]:
# Best paramete set
print('Best parameters found:\n', clf.best_params_)

# All results
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))


Best parameters found:
 {'activation': 'relu', 'alpha': 0.05, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.903 (+/-0.016) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.889 (+/-0.021) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'adam'}
0.891 (+/-0.021) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.883 (+/-0.025) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.901 (+/-0.031) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.888 (+/-0.010) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solve

In [ ]:
end = time.time()

print(f"Runtime of the program is {end - start}") 192/ 0.013

Runtime of the program is 210.70811533927917


In [ ]:
import time
start = time.time() 

y_true, y_pred = test_labels , clf.predict(test_features)

from sklearn.metrics import classification_report, confusion_matrix
print('Results on the test set:')
print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

end = time.time()

print(f"Runtime of the program is {end - start}")

Results on the test set:
              precision    recall  f1-score   support

           0       0.90      0.93      0.92       104
           1       0.92      0.89      0.90        96

    accuracy                           0.91       200
   macro avg       0.91      0.91      0.91       200
weighted avg       0.91      0.91      0.91       200

[[97  7]
 [11 85]]
Runtime of the program is 0.010601282119750977


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_true, y_pred))

0.91


In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(train_features, train_labels)
clf.predict_proba(test_features[:1])

array([[0.02612698, 0.97387302]])

In [ ]:
clf.predict(test_features[:1000, :])

In [ ]:
clf.score(test_features, test_labels)

0.9178378378378378

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
clf = MLPClassifier.mlp(kernel='linear')

AttributeError: ignored

In [ ]:
scores = cross_val_score(clf, test_labels, y_pred, cv=5)

In [ ]:

scores = cross_val_score(clf, features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.880 (std: 0.026)



In [ ]:
2000: 10min 20 Min     ///// 1000 = 5 Min +  cv: 10min

#**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=20, random_state=0)
rf.fit(train_features, train_labels)
y_pred1 = rf.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred1))
print(confusion_matrix(test_labels, y_pred1))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1918
           1       0.90      0.84      0.87      1854

    accuracy                           0.88      3772
   macro avg       0.88      0.87      0.88      3772
weighted avg       0.88      0.88      0.88      3772

[[1746  172]
 [ 298 1556]]


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, y_pred1))

0.8753976670201484


In [ ]:
scores = cross_val_score(rf, features, labels, cv=5)

In [ ]:
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.883 (std: 0.007)



In [ ]:
scores = cross_val_score(rf, features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.869 (std: 0.017)



#**Naive Bayes**

#Gaussian

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_features, train_labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(test_features)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(test_labels, y_pred))

Accuracy: 0.8


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred))
print(confusion_matrix(test_labels, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.84      0.81      1914
           1       0.82      0.76      0.79      1886

    accuracy                           0.80      3800
   macro avg       0.80      0.80      0.80      3800
weighted avg       0.80      0.80      0.80      3800

[[1609  305]
 [ 455 1431]]


*Cross Validation*

In [ ]:
scores = cross_val_score(gnb, test_labels, y_pred, cv=5)

In [ ]:

scores = cross_val_score(gnb, features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.816 (std: 0.016)



#**Optimized SVC**

In [ ]:
from sklearn.svm import SVC

In [ ]:
model = SVC()

In [ ]:
model.fit(train_features, train_labels)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction = model.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,prediction))
print(confusion_matrix(test_labels, prediction))

              precision    recall  f1-score   support

           0       0.90      0.97      0.94      1559
           1       0.94      0.83      0.88       913

    accuracy                           0.92      2472
   macro avg       0.92      0.90      0.91      2472
weighted avg       0.92      0.92      0.92      2472

[[1513   46]
 [ 159  754]]


In [ ]:
param_grid = {'C':[1,10],'gamma':[1,0.1], 'kernel':['linear','rbf']}


In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)

In [ ]:
grid.fit(train_features,train_labels)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...................... C=1, gamma=1, kernel=linear, total=  32.9s
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   32.9s remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=  33.1s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=  33.8s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=  33.6s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=  32.4s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total= 2.4min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total= 2.4min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total= 2.4min
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] .

[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed: 66.4min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10], 'gamma': [1, 0.1],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [ ]:
grid.param_grid

{'C': [1, 10], 'gamma': [1, 0.1], 'kernel': ['linear', 'rbf']}

In [ ]:
predic = grid.predict(test_features)

In [ ]:
print(classification_report(test_labels,predic))
print(confusion_matrix(test_labels, predic))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94      1559
           1       0.95      0.81      0.88       913

    accuracy                           0.92      2472
   macro avg       0.93      0.89      0.91      2472
weighted avg       0.92      0.92      0.91      2472

[[1524   35]
 [ 175  738]]


#**Random Forest Optimized**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(random_state=42)

In [ ]:
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [ ]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(train_features, train_labels)

In [ ]:
CV_rfc.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'max_features': 'auto',
 'n_estimators': 500}

In [ ]:
rfc1=RandomForestClassifier(random_state=42, max_features='auto', n_estimators= 200, max_depth=8, criterion='gini')

In [ ]:
rfc1.fit(train_features, train_labels)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:

pred=rfc1.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,pred))
print(confusion_matrix(test_labels, pred))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90      1061
           1       0.92      0.83      0.88       911

    accuracy                           0.89      1972
   macro avg       0.90      0.89      0.89      1972
weighted avg       0.89      0.89      0.89      1972

[[998  63]
 [153 758]]


In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy for Random Forest on CV data: ",accuracy_score(test_labels,pred))

Accuracy for Random Forest on CV data:  0.8950304259634888


#**XGBoost**

In [ ]:
import xgboost as xgb
modelxgb=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
modelxgb.fit(train_features, train_labels)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
predxgb = modelxgb.predict(test_features)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,predxgb))
print(confusion_matrix(test_labels, predxgb))

              precision    recall  f1-score   support

           0       0.87      0.87      0.87      1914
           1       0.87      0.86      0.87      1886

    accuracy                           0.87      3800
   macro avg       0.87      0.87      0.87      3800
weighted avg       0.87      0.87      0.87      3800

[[1665  249]
 [ 257 1629]]


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, predxgb))

0.8668421052631579


In [ ]:
modelxgb.score(test_features,test_labels)


0.8694594594594595

In [ ]:
scores = cross_val_score(model, test_labels, test_features, cv=5)

In [ ]:
scores = cross_val_score(modelxgb, features, labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.873 (std: 0.014)



#**Optimized DT**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Same 3-step process

# 1. Instantiate
# default criterion=gini
# you can swap to criterion=entropy 
dtc = DecisionTreeClassifier(random_state=0)

# 2. Fit
dtc.fit(train_features, train_labels)

# 3. Predict, there're 4 features in the iris dataset
y_pred_class = dtc.predict(test_features)

In [ ]:
from sklearn import metrics

In [ ]:
# Accuracy
metrics.accuracy_score(test_labels, y_pred_class)

0.7873333333333333

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_labels,y_pred_class))
print(confusion_matrix(test_labels, y_pred_class))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79      3005
           1       0.78      0.79      0.79      2995

    accuracy                           0.79      6000
   macro avg       0.79      0.79      0.79      6000
weighted avg       0.79      0.79      0.79      6000

[[2343  662]
 [ 614 2381]]


In [ ]:
# Import
from sklearn.model_selection import GridSearchCV

# Define the parameter values that should be searched
sample_split_range = list(range(1, 50))

# Create a parameter grid: map the parameter names to the values that should be searched
# Simply a python dictionary
# Key: parameter name
# Value: list of values that should be searched for that parameter
# Single key-value pair for param_grid
param_grid = dict(min_samples_split=sample_split_range)

# instantiate the grid
dtc = DecisionTreeClassifier(random_state=0)
grid = GridSearchCV(dtc, param_grid, cv=10, scoring='accuracy')

# fit the grid with data
grid.fit(train_features, train_labels)

GridSearchCV(cv=10, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=0, splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'min_samples_split': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                                               1

In [ ]:

# Single best score achieved across all params (min_samples_split)
print(grid.best_score_)

# Dictionary containing the parameters (min_samples_split) used to generate that score
print(grid.best_params_)

# Actual model object fit with those best parameters
# Shows default parameters that we did not specify
print(grid.best_estimator_)

In [ ]:
# Entropy of child 1 = 0
# Perfect split for this child

# Entropy of child 2 = 0.918
-(2/3)*np.log2(2/3) - (1/3)*np.log2(1/3)

In [ ]:
# Weighted average of entropy(children)
(3/4)*(0.9184) + (1/4)*0

In [ ]:
# Entropy Gain
1 - (3/4)*(0.9184) + (1/4)*0

#**KNN**

In [ ]:
#import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

#Setup arrays to store training and test accuracies
neighbors = np.arange(1,9)
train_accuracy =np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

for i,k in enumerate(neighbors):
    #Setup a knn classifier with k neighbors
    knn = KNeighborsClassifier(n_neighbors=k)
    
    #Fit the model
    knn.fit(train_features, train_labels)
    
    #Compute accuracy on the training set
    train_accuracy[i] = knn.score(train_features, train_labels)
    
    #Compute accuracy on the test set
    test_accuracy[i] = knn.score(test_features, test_labels) 

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [ ]:
#Generate plot
plt.title('k-NN Varying number of neighbors')
plt.plot(neighbors, test_accuracy, label='Testing Accuracy')
plt.plot(neighbors, train_accuracy, label='Training accuracy')
plt.legend()
plt.xlabel('Number of neighbors')
plt.ylabel('Accuracy')
plt.show()

In [ ]:
knn = KNeighborsClassifier(n_neighbors=7)

In [ ]:
#Fit the model
knn.fit(train_features,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [ ]:
knn.score(test_features,test_labels)

0.883421052631579

In [ ]:
y_pred = knn.predict(test_features)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels,y_pred))
from sklearn.metrics import classification_report
print(classification_report(test_labels,y_pred))

[[1690  224]
 [ 219 1667]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88      1914
           1       0.88      0.88      0.88      1886

    accuracy                           0.88      3800
   macro avg       0.88      0.88      0.88      3800
weighted avg       0.88      0.88      0.88      3800



In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, y_pred))

0.883421052631579


In [ ]:
scores = cross_val_score(knn, test_features, test_labels, cv=5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )
#88%

mean: 0.877 (std: 0.007)

